---
title: "Approach Shot Table"
author: "Shiyu Murashima (205581974)"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(dplyr)
library(ggplot2)

# Approach Shot Table Function
approach_table <- function(data, player){
  df1 <- data %>% 
    reframe("approachPercent" = (length(which(isApproach == 1 & shotHitBy == player & is.na(isWinner))) /
                                   length(isApproach))*100,
            "approachWin" = (length(which(isApproach == 1 & shotHitBy == player & is.na(isWinner) & isPointEnd == 1)) /
                               length(isApproach))*100,
            "approachVolleyWin" = (length(which(isApproach == 1 & shotHitBy == player & is.na(isWinner) & 
                                                  isPointEnd == 1 & isVolley == 1)) /
                                     length(isApproach))*100,
            "approachVolleyLose" = (length(which(isApproach == 1 & shotHitBy == player & is.na(isWinner) & 
                                                   isPointEnd != 1 & isVolley == 1)) /
                                      length(isApproach))*100)
  
  # temp_df <- data
  # temp_df$returnData <- ifelse(grepl("^Forehand", data$returnData), "Forehand", 
  #        ifelse(grepl("^Backhand", data$returnData), "Backhand", NA))
  # temp_df$shotType <- ifelse(grepl("^Forehand", data$shotType), "Forehand", 
  #        ifelse(grepl("^Backhand", data$shotType), "Backhand", NA))
  
  df2 <- data %>% 
    filter(isApproach == 1) %>% 
    summarise("approachFH" = (length(which((shotHitBy == player & shotFhBh == "Forehand")))) /
                (length(which(shotHitBy == player & (shotFhBh == "Forehand" | shotFhBh == "Backhand"))))*100,
              "approachBH" = (length(which((shotHitBy == player & shotFhBh == "Backhand")))) /
                (length(which(shotHitBy == player & (shotFhBh == "Forehand" | shotFhBh == "Backhand"))))*100,
              "approachFHWin" = (length(which((shotHitBy == player & shotFhBh == "Forehand" & isPointEnd == 1)))) /
                (length(which(shotHitBy == player & (shotFhBh == "Forehand" | shotFhBh == "Backhand"))))*100,
              "approachBHWin" = (length(which((shotHitBy == player & shotFhBh == "Backhand" & isPointEnd == 1)))) /
                (length(which(shotHitBy == player & (shotFhBh == "Forehand" | shotFhBh == "Backhand"))))*100)
  
  df3 <- data %>% 
    filter(isApproach == 1) %>% 
    summarise("forehandCross" = ((length(which(shotHitBy == player & shotFhBh == "Forehand" & shotDirection == "Crosscourt"))) /
                                   (length(which(shotHitBy == player & shotFhBh == "Forehand" & shotDirection == "Crosscourt")) +
                                   (length(which(shotHitBy == player & shotFhBh == "Forehand" & shotDirection == "Down the Line")))))*100,
              "forehandDL" = ((length(which(shotHitBy == player & shotFhBh == "Forehand" & shotDirection == "Down the Line"))) /
                                   (length(which(shotHitBy == player & shotFhBh == "Forehand" & shotDirection == "Crosscourt")) +
                                   (length(which(shotHitBy == player & shotFhBh == "Forehand" & shotDirection == "Down the Line")))))*100,
              "backhandCross" = ((length(which(shotHitBy == player & shotFhBh == "Backhand" & shotDirection == "Crosscourt"))) /
                                   (length(which(shotHitBy == player & shotFhBh == "Backhand" & shotDirection == "Crosscourt")) +
                                   (length(which(shotHitBy == player & shotFhBh == "Backhand" & shotDirection == "Down the Line")))))*100,
              "backhandDL" = ((length(which(shotHitBy == player & shotFhBh == "Backhand" & shotDirection == "Down the Line"))) /
                                   (length(which(shotHitBy == player & shotFhBh == "Backhand" & shotDirection == "Crosscourt")) +
                                   (length(which(shotHitBy == player & shotFhBh == "Backhand" & shotDirection == "Down the Line")))))*100)
  
  
  df <- data.frame(df1, df2, df3)
  data.frame("Stat" = colnames(df),
             "Percent" = round(as.numeric(unlist(df[1,])), digits = 1))
}

# Approach Shot Count Function
approach_count <- function(data, player){
  data %>% 
    filter(shotHitBy == player) %>% 
    reframe("approachShotCount" = length(which(isApproach == 1)),
            "approachVolleyCount" = length(which(isApproach == 1 & isVolley == 1)))
}

# Approach Shot Plot Function
approach_plot <- function(data){
  data$Stat <- factor(c("Approach %", "Approach Win %", "Volley Win %", "Volley Lose %", 
                        "FH %", "BH %", "FH Win %", "BH Win %", "FH CC %", "FH DTL %", "BH CC %", "BH DTL %"))
  data$Category <- c(rep("Approach Win", 4), rep("Forehand vs Backhand", 4), rep("Forehand", 2), rep("Backhand", 2))
  
  ggplot(data[9:12,], aes(x = Category, y = Percent, fill = Stat)) + 
    geom_bar(position="stack", stat="identity") +
    geom_text(aes(label = Percent), position = position_stack(vjust = 0.5), cex = 6) +
    geom_text(aes(label = Stat), position = position_stack(vjust = 0.5), vjust = 3) +
    scale_fill_manual(values = c("#2D68C4", "#F2A900", "#2D68C4", "#F2A900")) +
    theme(legend.position = "none", 
          plot.title = element_text(hjust = 0.5),
          axis.title.y = element_blank(),
          panel.background = element_rect(fill = "white"),
          panel.grid.major.x = element_line(color = "gray95"),
          panel.grid.minor.x = element_blank(),
          panel.grid.major.y = element_blank(),
          panel.grid.minor.y = element_blank()) +
    labs(title = "Approach FH vs BH, CC vs DTL") +
    coord_flip()
}
```

```{r}
data <- read.csv("HanceRapoluFullMatch.csv")
player <- "Kimmi Hance"
df <- approach_table(data, player)
df

approach_count(data, player)
approach_plot(df)
```
