---
title: "Quick Statistics"
author: "Shiyu Murashima (205581974)"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(dplyr)

# Quick Statistics Function
quick_percentages <- function(data, player){
  data$courtSide <- ifelse(data$pointScore %in% c("15-0", "15-30", "30-40", "40-0", "40-40 (Ad)",
                                            "0-15", "30-15", "40-30", "0-40"),
                       "Ad", 
                       ifelse(data$pointScore %in% c("15-40", "30-0", "30-30", "15-15", "40-40 (Deuce)",
                                                   "40-15", "0-30", "0-0"),
                              "Deuce",
                              NA))
  
  ad_serve <- data %>% 
  filter(serverName == player & courtSide == "Ad") %>% 
  summarise("Server Name" = player,
            "Ad Serve Wide %" = round(((length(which(firstServeZone == "Wide")) + length(which(secondServeZone == "Wide"))) /
              (length(which(firstServeZone != "")) + length(which(secondServeZone != ""))))*100),
            "Ad Serve Body %" = round(((length(which(firstServeZone == "Body")) + length(which(secondServeZone == "Body"))) /
              (length(which(firstServeZone != "")) + length(which(secondServeZone != ""))))*100),
            "Ad Serve T %" = round(((length(which(firstServeZone == "T")) + length(which(secondServeZone == "T"))) /
              (length(which(firstServeZone != "")) + length(which(secondServeZone != ""))))*100))
  
  deuce_serve <- data %>% 
  filter(serverName == player & courtSide == "Deuce") %>% 
  summarise("Deuce Serve Wide %" = round(((length(which(firstServeZone == "Wide")) + length(which(secondServeZone == "Wide"))) /
              (length(which(firstServeZone != "")) + length(which(secondServeZone != ""))))*100),
            "Deuce Serve Body %" = round(((length(which(firstServeZone == "Body")) + length(which(secondServeZone == "Body"))) /
              (length(which(firstServeZone != "")) + length(which(secondServeZone != ""))))*100),
            "Deuce Serve T %" = round(((length(which(firstServeZone == "T")) + length(which(secondServeZone == "T"))) /
              (length(which(firstServeZone != "")) + length(which(secondServeZone != ""))))*100))
  
  cbind(ad_serve, deuce_serve)
}

quick_counts <- function(data, player){
  temp_df <- data
  temp_df$returnData <- ifelse(grepl("^Forehand", data$returnData), "Forehand", 
         ifelse(grepl("^Backhand", data$returnData), "Backhand", NA))
  temp_df$shotType <- ifelse(grepl("^Forehand", data$shotType), "Forehand", 
         ifelse(grepl("^Backhand", data$shotType), "Backhand", NA))
 
  error_table <- temp_df %>% 
    filter(shotHitBy == player & is.na(isWinner)) %>% 
    summarise("Server Name" = player,
              "FH Error Net Count" = length(which((returnData == "Forehand" | shotType == "Forehand") & isErrorNet == 1)),
              "FH Error Wide Count" = length(which(((returnData == "Forehand" | shotType == "Forehand") & 
                                         (isErrorWideL == 1 | isErrorWideR == 1)))),
              "FH Error Long Count" = length(which((returnData == "Forehand" | shotType == "Forehand") & isErrorLong == 1)),
              "BH Error Net Count" = length(which((returnData == "Backhand" | shotType == "Backhand") & isErrorNet == 1)),
              "BH Error Wide Count"= length(which(((returnData == "Backhand" | shotType == "Backhand") & 
                                        (isErrorWideL == 1 | isErrorWideR == 1)))),
              "BH Error Long Count" = length(which((returnData == "Backhand" | shotType == "Backhand") & isErrorLong == 1)))
  
  net_table <- data %>% 
    filter(shotHitBy == player) %>% 
    summarise("Net Count" = length(which(isVolley == 1)))
  
  cbind(error_table, net_table)
}
```

```{r}
library(reactablefmtr)
library(htmltools)

df <- read.csv("NandaPerotFullMatch.csv")
percent_data <- rbind(quick_percentages(df, "Govind Nanda"), quick_percentages(df, "Raphael Perot"))
count_data <- rbind(quick_counts(df, "Govind Nanda"), quick_counts(df, "Raphael Perot"))
reactable(percent_data, theme = fivethirtyeight())
reactable(count_data, theme = fivethirtyeight())
```

```{r}
df <- read.csv("HanceRapoluFullMatch.csv")
rbind(quick_stats(df, "Kimmi Hance"), quick_stats(df, "Malaika Rapolu"))
```

```{r}
# Fix
ad_serve <- df %>% 
  filter(serverName == "Govind Nanda" & courtSide == "Ad") %>% 
  summarise("adWide" = ((length(which(firstServeZone == "Wide")) + length(which(secondServeZone == "Wide"))) /
              (length(which(firstServeZone != "")) + length(which(secondServeZone != ""))))*100,
            "adBody" = ((length(which(firstServeZone == "Body")) + length(which(secondServeZone == "Body"))) /
              (length(which(firstServeZone != "")) + length(which(secondServeZone != ""))))*100,
            "adT" = ((length(which(firstServeZone == "T")) + length(which(secondServeZone == "T"))) /
              (length(which(firstServeZone != "")) + length(which(secondServeZone != ""))))*100)
            # "adWideWin" = (length(which(firstServeZone == "Wide" & isPointEnd == 1)) +
            #                length(which(secondServeZone == "Wide" & isPointEnd == 1))) /
            #   (length(which(firstServeZone != "")) + length(which(secondServeZone != ""))),
            # "adBodyWin" = (length(which(firstServeZone == "Body" & isPointEnd == 1)) + 
            #             length(which(secondServeZone == "Body" & isPointEnd ==1))) /
            #   (length(which(firstServeZone != "")) + length(which(secondServeZone != ""))),
            # "adTWin" = (length(which(firstServeZone == "T" & isPointEnd == 1)) + 
            #          length(which(secondServeZone == "T" & isPointEnd == 1))) /
            #   (length(which(firstServeZone != "")) + length(which(secondServeZone != ""))))

deuce_serve <- df %>% 
  filter(serverName == "Govind Nanda" & courtSide == "Deuce") %>% 
  summarise("deuceWide" = ((length(which(firstServeZone == "Wide")) + length(which(secondServeZone == "Wide"))) /
              (length(which(firstServeZone != "")) + length(which(secondServeZone != ""))))*100,
            "deuceBody" = ((length(which(firstServeZone == "Body")) + length(which(secondServeZone == "Body"))) /
              (length(which(firstServeZone != "")) + length(which(secondServeZone != ""))))*100,
            "deuceT" = ((length(which(firstServeZone == "T")) + length(which(secondServeZone == "T"))) /
              (length(which(firstServeZone != "")) + length(which(secondServeZone != ""))))*100)
            # "deuceWideWin" = (length(which(firstServeZone == "Wide" & isPointEnd == 1)) +
            #                length(which(secondServeZone == "Wide" & isPointEnd == 1))) /
            #   (length(which(firstServeZone != "")) + length(which(secondServeZone != ""))),
            # "deuceBodyWin" = (length(which(firstServeZone == "Body" & isPointEnd == 1)) + 
            #             length(which(secondServeZone == "Body" & isPointEnd ==1))) /
            #   (length(which(firstServeZone != "")) + length(which(secondServeZone != ""))),
            # "deuceTWin" = (length(which(firstServeZone == "T" & isPointEnd == 1)) + 
            #          length(which(secondServeZone == "T" & isPointEnd == 1))) /
            #   (length(which(firstServeZone != "")) + length(which(secondServeZone != ""))))
```

