---
title: "Shot Cross DTL %"
author: "Tony He"
date: "2024-02-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries
```{r}
library(png)
library(readr)
library(dplyr)
library(grid)
library(ggplot2)
library(ggpubr)
library(ggtext)
library(reshape2)
library(gridExtra)
```

# Loading in Data
```{r}
shotdata <- read.csv("Shot_Visuals_EliseWagle_NatalieDuffy.csv")
player <- "Elise Wagle"
grid <- readPNG("Full_Court.png")
```

# Data Manipulation and Plotting
```{r}
# Volley Distribution Function
volley_distribution <- function(shotdata, player) {
  
    ad_backhand_perc <- shotdata %>% 
                     filter(shotFhBh == "Backhand" & shotHitBy == player & side == "Ad") %>% 
                     summarise("Type" = "Backhand_perc_ad",
                               "Ad_DTL" = round(((length(which((shotDirection == "Down the Line")))) /
                                 (length(shotDirection)))*100),
                               "Ad_CC" = round(((length(which((shotDirection == "Crosscourt")))) /
                                 (length(shotDirection)))*100))
    
    deuce_backhand_perc <- shotdata %>% 
                        filter(shotFhBh == "Backhand" & shotHitBy == player & side == "Deuce") %>% 
                        summarise("Type" = "Backhand_perc_deuce",
                               "Deuce_DTL" = round(((length(which((shotDirection == "Down the Line")))) /
                                 (length(shotDirection)))*100),
                               "Deuce_CC" = round(((length(which((shotDirection == "Crosscourt")))) /
                                 (length(shotDirection)))*100))
    
    ad_forehand_perc <- shotdata %>% 
                       filter(shotFhBh == "Forehand" & shotHitBy == player & side == "Ad") %>% 
                        summarise("Type" = "forehand_perc_ad",
                               "Ad_DTL" = round(((length(which((shotDirection == "Down the Line")))) /
                                 (length(shotDirection)))*100),
                               "Ad_CC" = round(((length(which((shotDirection == "Crosscourt")))) /
                                 (length(shotDirection)))*100))

    deuce_forehand_perc <- shotdata %>% 
                          filter(shotFhBh == "Forehand" & shotHitBy == player & side == "Deuce") %>% 
                        summarise("Type" = "forehand_perc_deuce",
                               "Deuce_DTL" = round(((length(which((shotDirection == "Down the Line")))) /
                                 (length(shotDirection)))*100),
                               "Deuce_CC" = round(((length(which((shotDirection == "Crosscourt")))) /
                                 (length(shotDirection)))*100))
    
    df <- rbind(cbind(ad_backhand_perc, deuce_backhand_perc), cbind(ad_forehand_perc , deuce_forehand_perc))
    
    g <- rasterGrob(grid, width=unit(1,"npc"), height=unit(1,"npc"), interpolate = FALSE)
  
    
    # Backhand plot
    backhand_plot <- ggplot() +
    labs(title = paste("Backhand shot %", player), x = "", y = "") +
    xlim(0, 10) +
    ylim(0, 10) +
    annotation_custom(g, xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf) +
    theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),
          axis.text.y = element_blank(), axis.ticks.y = element_blank(),
          axis.title.x = element_blank(), axis.title.y = element_blank(),
          plot.title = element_text(hjust = 0.5, face = "bold")) + coord_fixed() +
      
    # Labels
    annotate("text", x=3.2, y=0.25, label= paste0("Ad"), cex = 4.5, fontface = 2, col = 'white', family = "Tahoma") +
    annotate("text", x=6.8, y=0.25, label= paste0("Deuce"), cex = 4.5, fontface = 2, col = 'white', family = "Tahoma") +
    annotate("text", x=0.9, y=4.95, label= paste0("Net"), cex = 4.5, fontface = 2, col = 'white', family = "Tahoma") +
    
    # Ad Down the Line
    annotate("text", x=3, y=7.9, label= paste0(df$Ad_DTL[1], "%"), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=2.5, y=8.75, label= paste0("Down the Line"), cex = 1.5, fontface = 2, col = 'white', family = "Tahoma") +
    
    # Ad Crosscourt
    annotate("text", x=5.9, y=7.9, label= paste0(df$Ad_CC[1], "%"), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=5.9, y=8.75, label= paste0("Crosscourt"), cex = 1.5, fontface = 2, col = 'white', family = "Tahoma") +

    # Deuce Crosscourt
    annotate("text", x=4.1, y=7.9, label= paste0(df$Deuce_CC[1], "%"), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=4.1, y=8.75, label= paste0("Crosscourt"), cex = 1.5, fontface = 2, col = 'white', family = "Tahoma") +

    # Deuce Down the Line
    annotate("text", x=7, y=7.9, label= paste0(df$Deuce_DTL[1], "%"), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=7.5, y=8.75, label= paste0("Down the Line"), cex = 1.5, fontface = 2, col = 'white', family = "Tahoma") +
    # Arrows
    annotate("segment", x = 3, y = 0.6, xend = 3, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
    annotate("segment", x = 3, y = 0.6, xend = 5.9, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
    annotate("segment", x = 7, y = 0.6, xend = 4.1, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
    annotate("segment", x = 7, y = 0.6, xend = 7, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last"))
    
  # Forehand plot
    forehand_plot  <- ggplot() +
    labs(title = paste("Forehand shot %", player), x = "", y = "") +
    xlim(0, 10) +
    ylim(0, 10) +
    annotation_custom(g, xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf) +
    theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),
          axis.text.y = element_blank(), axis.ticks.y = element_blank(),
          axis.title.x = element_blank(), axis.title.y = element_blank(),
          plot.title = element_text(hjust = 0.5, face = "bold")) + coord_fixed() +
      
    # Labels
    annotate("text", x=3.2, y=0.25, label= paste0("Ad"), cex = 4.5, fontface = 2, col = 'white', family = "Tahoma") +
    annotate("text", x=6.8, y=0.25, label= paste0("Deuce"), cex = 4.5, fontface = 2, col = 'white', family = "Tahoma") +
    annotate("text", x=0.9, y=4.95, label= paste0("Net"), cex = 4.5, fontface = 2, col = 'white', family = "Tahoma") +
    
    # Ad Down the Line
    annotate("text", x=3, y=7.9, label= paste0(df$Ad_DTL[2], "%"), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=2.5, y=8.75, label= paste0("Down the Line"), cex = 1.5, fontface = 2, col = 'white', family = "Tahoma") +
    
    # Ad Crosscourt
    annotate("text", x=5.9, y=7.9, label= paste0(df$Ad_CC[2], "%"), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=5.9, y=8.75, label= paste0("Crosscourt"), cex = 1.5, fontface = 2, col = 'white', family = "Tahoma") +

    # Deuce Crosscourt
    annotate("text", x=4.1, y=7.9, label= paste0(df$Deuce_CC[2], "%"), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=4.1, y=8.75, label= paste0("Crosscourt"), cex = 1.5, fontface = 2, col = 'white', family = "Tahoma") +

    # Deuce Down the Line
    annotate("text", x=7, y=7.9, label= paste0(df$Deuce_DTL[2], "%"), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=7.5, y=8.75, label= paste0("Down the Line"), cex = 1.5, fontface = 2, col = 'white', family = "Tahoma") +
    # Arrows
    annotate("segment", x = 3, y = 0.6, xend = 3, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
    annotate("segment", x = 3, y = 0.6, xend = 5.9, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
    annotate("segment", x = 7, y = 0.6, xend = 4.1, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
    annotate("segment", x = 7, y = 0.6, xend = 7, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last"))
  
  grid.arrange(forehand_plot,backhand_plot ,nrow=1)
}

volley_distribution(shotdata, player)
```
