---
title: "ErrorTableTemplate"
author: "Tony Jeon"
date: "2024-01-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Libraries
```{r}
library(knitr)
```

### Propotion of Break Points Won
```{r}
breakPoint <- function(match, firstName, lastName) {
  # Clean data for all break points for UCLA player
  bpData <- match[((match$returnerName == paste(firstName, lastName)) & (match$isBreakPoint == "True")), ]
  isSet1 <- bpData$setScore == "0-0"
  isSet2 <- bpData$setScore == "0-1" | bpData$setScore == "1-0" 
  isSet3 <- bpData$setScore == "1-1" 
  bpWon <- bpData$pointWonBy == paste(firstName, lastName)
  bpData$breakPointWon[bpWon] <- TRUE
  bpData$breakPointWon[!bpWon] <- FALSE
  
  # Set 1
  set1Data <- bpData[isSet1, ]
  set1_DF <- data.frame(sum(set1Data$breakPointWon), paste0(as.character(round(sum(set1Data$breakPointWon) / nrow(set1Data) * 100, 2)), "%"))
  colnames(set1_DF) <- c("Break Points Won", "Break Point Win Percentage")
  
  # Set 2
  set2Data <- bpData[isSet2, ]
  set2_DF <- data.frame(sum(set2Data$breakPointWon), paste0(as.character(round(sum(set2Data$breakPointWon) / nrow(set2Data) * 100, 2)), "%"))
  colnames(set2_DF) <- c("Break Points Won", "Break Point Win Percentage")
  bpDF <- rbind(set1_DF, set2_DF)
  rownames(bpDF) <- c("Set 1", "Set 2")
  
    # Set 3 
  if (any(isSet3)) {
    set3Data <- bpData[isSet3, ]
    set3_DF <- data.frame(sum(set3Data$breakPointWon), paste0(as.character(round(sum(set3Data$breakPointWon) / nrow(set3Data) * 100, 2)), "%"))
    colnames(set3_DF) <- c("Break Points Won", "Break Point Win Percentage")
    rownames(set3_DF) <- "Set 3"
    bpDF <- rbind(bpDF, set3_DF)
  }
  
  # Full Match
  total_DF <- data.frame(sum(bpData$breakPointWon), paste0(as.character(round(sum(bpData$breakPointWon) / nrow(bpData) * 100, 2)), "%"))
  colnames(total_DF) <- c("Break Points Won", "Break Point Win Percentage")
  rownames(total_DF) <- "Full Match"
  bpDF <- rbind(bpDF, total_DF)
  kable(bpDF, align = "ccc")
}
```


```{r}
# matchData <- read.csv("SpencerNewPoint.csv", header = TRUE)
matchData2 <- read.csv("NandaPerotPoint.csv", header = TRUE)
# breakPoint(matchData, "Spencer", "Johnson")
breakPoint(matchData2, "Govind", "Nanda")
```