---
title: "Tennis Visualizations"
author: "Shiyu Murashima"
date: "`r Sys.Date()`"
output: html_document
---

# Libraries
```{r}
library(dplyr)
library(readr)
library(knitr)
library(tidyr)
library(tidyverse)
library(png)
library(ggplot2)
library(ggpubr)
library(ggtext)
library(gghighlight)
library(reshape)
library(reshape2)
library(grid)
library(gridExtra)
library(zoo)
```

# Loading in Data
```{r}
shotdata <- read.csv("Shot_Visuals_EliseWagle_MotkaKomac.csv")
pointdata <- read.csv("Point_Visuals_EliseWagle_MotkaKomac.csv")

# Assuming pointdata is a data frame or list containing player names
player1 <- pointdata$player1Name[1]
player2 <- pointdata$player2Name[1]

grid1 <- readPNG("courtImages/serve_placement_court_new.png")
grid2 <- readPNG("courtImages/Court_Image_Volleys.png")
grid3 <- readPNG("courtImages/Tennis_Court_Dark_With_Background.png")
```

# Summary Stats
```{r}
col_names <- c("1st Serve In %", "2nd Serve In %", "1st Serve Won %", "2nd Serve Won %", "Service Points Won %", 
               "Return Points Won %", "Ace (Count)", "Double Fault (Count)")

percent_table <- function(pointdata, player){
  
  serveIn <- pointdata %>% 
    filter(serverName == player) %>% 
    summarise("firstServeInPercent" = (length(which((serveResult == "1st Serve In"))) / 
                length(which((serverName == player))))*100,
              "secondServeInPercent" = (length(which((serveResult == "2nd Serve In"))) / 
                length(which((serveResult == "2nd Serve In" | serveResult == "Double Fault"))))*100)
  
  firstServeWon <- pointdata %>% 
    filter(serverName == player & serveResult == "1st Serve In") %>% 
    summarise("firstServeWonPercent" = (length(which(pointWonBy == player)) / length(pointWonBy))*100)
  
  secondServeWon <- pointdata %>% 
    filter(serverName == player & serveResult == "2nd Serve In") %>% 
    summarise("secondServeWonPercent" = (length(which(pointWonBy == player)) / length(pointWonBy))*100)

  servicePointsWon <- pointdata %>% 
    filter(serverName == player) %>% 
    summarise("servicePointsWonPercent" = ((length(which(pointWonBy == player))) /
                (length(which(serverName == player))))*100)

  returnPointsWon <- pointdata %>% 
    filter(serverName != player) %>% 
    summarise("returnPointsWonPercent" = ((length(which(pointWonBy == player))) /
                (length(which(serverName != player))))*100)
  
  aceDoubleFault <- pointdata %>% 
    filter(serverName == player) %>%
    summarise("aceCount" = sum(isAce == "True" |isAce == "True" |isAce == TRUE, na.rm = TRUE),
              "doubleFaultCount" = sum(serveResult == "Double Fault", na.rm = TRUE))

  temp_df <- data.frame(serveIn, firstServeWon, secondServeWon, 
                         servicePointsWon, returnPointsWon, aceDoubleFault)

  data <- data.frame("Stat" = col_names, 
                     "Percent" = round(as.numeric(unlist(temp_df[1,])), digits = 1))
  
  data$Stat <- factor(data$Stat, levels = c("1st Serve In %", "2nd Serve In %", "1st Serve Won %", 
                                            "2nd Serve Won %", "Service Points Won %", "Return Points Won %",
                                            "Ace (Count)","Double Fault (Count)"))
  
  data
}

sum_plot <- function(data){
  server_order <- unique(data$Server)
  data$Server <- factor(data$Server, levels = server_order)
  
  ggplot(data, aes(Stat, Percent)) +
    geom_bar(stat = "identity", aes(fill = Server), position = "dodge") +
    geom_label(aes(label = Percent), colour = "black", cex = 5) +
    labs(title = "Summary Statistics", x = "", size = 12) +
    theme(plot.title = element_text(hjust = 0.5),
          strip.text = element_text(size = 12),
          strip.background = element_rect(fill = "gray95"),
          panel.background = element_rect(fill = "white"),
          panel.grid.major.x = element_line(color = "gray95"),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          panel.grid.major.y = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_text(size = 12),
          axis.ticks.x = element_blank(),
          axis.ticks.y = element_blank(),
          legend.position = "none") + 
    coord_flip() +
    facet_grid(. ~ Server, scales = "free_y") +
    scale_fill_manual(values = c("#2D68C4", "#F2A900")) +
    scale_x_discrete(limits = rev(levels(data$Stat)))
}

percentA <- data.frame(Server = player1, percent_table(pointdata, player1))
percentB <- data.frame(Server = player2, percent_table(pointdata, player2))
percent_df <- rbind(percentA, percentB)
p1 <- sum_plot(percent_df)
p2 <- p1 + scale_y_reverse()
g1 <- ggplotGrob(p1)
g2 <- ggplotGrob(p2)
g1$grobs[grep("panel-1-1", g1$layout$name)] <- g2$grobs[grep("panel-1-1", g2$layout$name)]
g1$grobs[grep('axis-b-1', g1$layout$name)] <- g2$grobs[grep('axis-b-2', g2$layout$name)]
grid.newpage(); grid.draw(g1) # if you can't see the percents, try running this line in the console
```

# Serve Placement
```{r}
serve_placement <- function(pointdata, player){
  ad_serve_win <- pointdata %>% 
    filter(serverName == player) %>% 
    summarise("Type" = "Percent",
              "adServeWide" = round(((length(which((player1ServePlacement == "Ad: Wide") & pointWonBy == player))) /
                (length(which(player1ServePlacement == "Ad: Wide"))))*100),
              "adServeBody" = round(((length(which((player1ServePlacement == "Ad: Body") & pointWonBy == player))) /
                (length(which(player1ServePlacement == "Ad: Body"))))*100),
              "adServeT" = round(((length(which((player1ServePlacement == "Ad: T") & pointWonBy == player))) /
                (length(which(player1ServePlacement == "Ad: T"))))*100))
  
  deuce_serve_win <- pointdata %>% 
    filter(serverName == player) %>% 
    summarise("deuceServeWide" = round(((length(which((player1ServePlacement == "Deuce: Wide") & pointWonBy == player))) /
                (length(which(player1ServePlacement == "Deuce: Wide"))))*100),
              "deuceServeBody" = round(((length(which((player1ServePlacement == "Deuce: Body") & pointWonBy == player))) /
                (length(which(player1ServePlacement == "Deuce: Body"))))*100),
              "deuceServeT" = round(((length(which((player1ServePlacement == "Deuce: T") & pointWonBy == player))) /
                (length(which(player1ServePlacement == "Deuce: T"))))*100))
  
  ad_serve_count <- pointdata %>% 
    filter(serverName == player) %>% 
    summarise("Type" = "Count",
              "adServeWide" = length(which(player1ServePlacement == "Ad: Wide")),
              "adServeBody" = length(which(player1ServePlacement == "Ad: Body")),
              "adServeT" = length(which(player1ServePlacement == "Ad: T")))

  deuce_serve_count <- pointdata %>% 
    filter(serverName == player) %>% 
    summarise("deuceServeWide" = length(which(player1ServePlacement == "Deuce: Wide")),
              "deuceServeBody" = length(which(player1ServePlacement == "Deuce: Body")),
              "deuceServeT" = length(which(player1ServePlacement == "Deuce: T")))
  
  df <- rbind(cbind(ad_serve_win, deuce_serve_win), cbind(ad_serve_count, deuce_serve_count))
  
  g <- rasterGrob(grid1, width=unit(1,"npc"), height=unit(1,"npc"), interpolate = FALSE)
  
  ggplot(df) +
    annotation_custom(g, xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf) +
    annotate("rect", 
             xmin=c(0,1,2,3.05,4,5), 
             xmax=c(1,2,2.95,4,5,6), 
             ymin=c(0.1,0.1,0.1,0.1,0.1,0.1) ,
             ymax=c(9.9,9.9,9.9,9.9,9.9,9.9), 
             alpha=1, color="black", 
             fill=c(ifelse(df$adServeWide[2] >= 12, "goldenrod", ifelse(df$adServeWide[2] < 8, "lemonchiffon2", "lightgoldenrod2")),
                    ifelse(df$adServeBody[2] >= 12, "goldenrod", ifelse(df$adServeBody[2] < 8, "lemonchiffon2", "lightgoldenrod2")),
                    ifelse(df$adServeT[2] >= 12, "goldenrod", ifelse(df$adServeT[2] < 8, "lemonchiffon2", "lightgoldenrod2")),
                    ifelse(df$deuceServeT[2] >= 12, "goldenrod", ifelse(df$deuceServeT[2] < 8, "lemonchiffon2", "lightgoldenrod2")),
                    ifelse(df$deuceServeBody[2] >= 12, "goldenrod", ifelse(df$deuceServeBody[2] < 8, "lemonchiffon2", "lightgoldenrod2")),
                    ifelse(df$deuceServeWide[2] >= 12, "goldenrod", ifelse(df$deuceServeWide[2] < 8, "lemonchiffon2", "lightgoldenrod2")))) +
    
    annotate("text", x=0.5, y=1.5, label= "Wide", cex = 4) +
    annotate("text", x=1.5, y=1.5, label= "Body", cex = 4) +
    annotate("text", x=2.475, y=1.5, label= "T", cex = 4) +
    annotate("text", x=3.525, y=1.5, label= "T", cex = 4) +
    annotate("text", x=4.5, y=1.5, label= "Body", cex = 4) +
    annotate("text", x=5.5, y=1.5, label= "Wide", cex = 4) +
    annotate("text", x=1.5, y=0.5, label= "Ad Side", cex = 4) +
    annotate("text", x=4.5, y=0.5, label= "Deuce Side", cex = 4) +
    
    annotate("text", x=0.5, y=6, label= paste0(df$adServeWide[1], "%"), cex = 6, fontface = 2, 
             col = ifelse(df$adServeWide[1] >= 70, "darkgreen", ifelse(df$adServeWide[1] < 50, "red", "black"))) +
    annotate("text", x=1.5, y=6, label= paste0(df$adServeBody[1], "%"), cex = 6, fontface = 2, 
             col = ifelse(df$adServeBody[1] >= 70, "darkgreen", ifelse(df$adServeBody[1] < 50, "red", "black"))) +
    annotate("text", x=2.475, y=6, label= paste0(df$adServeT[1], "%"), cex = 6, fontface = 2, 
             col = ifelse(df$adServeT[1] >= 70, "darkgreen", ifelse(df$adServeT[1] < 50, "red", "black"))) +
    annotate("text", x=3.525, y=6, label= paste0(df$deuceServeT[1], "%"), cex = 6, fontface = 2, 
             col = ifelse(df$deuceServeT[1] >= 70, "darkgreen", ifelse(df$deuceServeT[1] < 50, "red", "black"))) +
    annotate("text", x=4.5, y=6, label= paste0(df$deuceServeBody[1], "%"), cex = 6, fontface = 2, 
             col = ifelse(df$deuceServeBody[1] >= 70, "darkgreen", ifelse(df$deuceServeBody[1] < 50, "red", "black"))) +
    annotate("text", x=5.5, y=6, label= paste0(df$deuceServeWide[1], "%"), cex = 6, fontface = 2, 
             col = ifelse(df$deuceServeWide[1] >= 70, "darkgreen", ifelse(df$deuceServeWide[1] < 50, "red", "black"))) +
  
    annotate("text", x=0.5, y=5.5, label= paste0("won"), cex = 4,
             col = ifelse(df$adServeWide[1] >= 70, "darkgreen", ifelse(df$adServeWide[1] < 50, "red", "black"))) +
    annotate("text", x=1.5, y=5.5, label= paste0("won"), cex = 4,
             col = ifelse(df$adServeBody[1] >= 70, "darkgreen", ifelse(df$adServeBody[1] < 50, "red", "black"))) +
    annotate("text", x=2.475, y=5.5, label= paste0("won"), cex = 4,
             col = ifelse(df$adServeT[1] >= 70, "darkgreen", ifelse(df$adServeT[1] < 50, "red", "black"))) +
    annotate("text", x=3.525, y=5.5, label= paste0("won"), cex = 4,
             col = ifelse(df$deuceServeT[1] >= 70, "darkgreen", ifelse(df$deuceServeT[1] < 50, "red", "black"))) +
    annotate("text", x=4.5, y=5.5, label= paste0("won"), cex = 4,
             col = ifelse(df$deuceServeBody[1] >= 70, "darkgreen", ifelse(df$deuceServeBody[1] < 50, "red", "black"))) +
    annotate("text", x=5.5, y=5.5, label= paste0("won"), cex = 4,
             col = ifelse(df$deuceServeWide[1] >= 70, "darkgreen", ifelse(df$deuceServeWide[1] < 50, "red", "black"))) +
    
    annotate("text", x=0.5, y=4.75, label= paste0("(", df$adServeWide[2], " shots)"), cex = 4, 
             fontface = ifelse(df$adServeWide[2] > 15, 2, 1)) +
    annotate("text", x=1.5, y=4.75, label= paste0("(", df$adServeBody[2], " shots)"), cex = 4, 
             fontface = ifelse(df$adServeBody[2] > 15, 2, 1)) +
    annotate("text", x=2.475, y=4.75, label= paste0("(", df$adServeT[2], " shots)"), cex = 4, 
             fontface = ifelse(df$adServeT[2] > 15, 2, 1)) +
    annotate("text", x=3.525, y=4.75, label= paste0("(", df$deuceServeT[2], " shots)"), cex = 4, 
             fontface = ifelse(df$deuceServeT[2] > 15, 2, 1)) +
    annotate("text", x=4.5, y=4.75, label= paste0("(", df$deuceServeBody[2], " shots)"), cex = 4, 
             fontface = ifelse(df$deuceServeBody[2] > 15, 2, 1)) +
    annotate("text", x=5.5, y=4.75, label= paste0("(", df$deuceServeWide[2], " shots)"), cex = 4, 
             fontface = ifelse(df$deuceServeWide[2] > 15, 2, 1)) +
    
    theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),
          axis.text.y = element_blank(), axis.ticks.y = element_blank(),
          axis.title.x = element_blank(), axis.title.y = element_blank(),
          plot.title = element_text(hjust = 0.5, face = "bold")) +
    labs(title = paste("Serve Placement -", player), x = "", y = "") +
    xlim(-0.73, 6.73) +
    ylim(0, 10)
}

serve_placement(pointdata, player1)
```

# Volley Distribution
```{r}
# Assuming you have a data frame named point_df with columns pointWonBy and pointNumber
example_df <- pointdata[, c('pointWonBy', 'pointNumber')]
colnames(example_df)[colnames(example_df) == 'pointWonBy'] <- 'pointWonBy_PV'
shot_merged <- merge(shotdata, example_df, by='pointNumber')

# Volley Distribution Function
volley_distribution <- function(shotdata, player) {
    ad_volley_win <- shot_merged %>%
      filter(isVolley == 1 & shotHitBy == player & side == "Ad") %>%
      summarise("Type" = "Win Percentage",
                "Ad_DTL" = round(length(unique(pointNumber[which(pointWonBy_PV == player & shotDirection == "Down the Line")])) /
                                   length(unique(pointNumber[shotDirection == "Down the Line"])) * 100),
                "Ad_CC" = round(length(unique(pointNumber[which(pointWonBy_PV == player & shotDirection == "Crosscourt")])) / 
                                  length(unique(pointNumber[shotDirection == "Crosscourt"])) * 100)) 
    
    deuce_volley_win <- shot_merged %>%
      filter(isVolley == 1 & shotHitBy == player & side == "Deuce") %>%
      summarise("Type" = "Win Percentage",
                "Deuce_DTL" = round(length(unique(pointNumber[which(pointWonBy_PV == player & shotDirection == "Down the Line")])) /
                                      length(unique(pointNumber[shotDirection == "Down the Line"])) * 100),
                "Deuce_CC" = round(length(unique(pointNumber[which(pointWonBy_PV == player & shotDirection == "Crosscourt")])) / 
                                     length(unique(pointNumber[shotDirection == "Crosscourt"])) * 100)) 
    
    ad_volley_count <- shot_merged %>% 
      filter(isVolley == 1 & shotHitBy == player & side == "Ad") %>% 
      summarise("Type" = "Count",
                "Ad_DTL" = round((length(which(shotDirection == "Down the Line")))),
                "Ad_CC" = round((length(which(shotDirection == "Crosscourt")))))

    deuce_volley_count <- shot_merged %>% 
      filter(isVolley == 1 & shotHitBy == player & side == "Deuce") %>% 
      summarise("Type" = "Count",
                "Deuce_DTL" = round((length(which(shotDirection == "Down the Line")))),
                "Deuce_CC" = round((length(which(shotDirection == "Crosscourt")))))
    
    df <- rbind(cbind(ad_volley_win, deuce_volley_win), cbind(ad_volley_count, deuce_volley_count))
    winPercentVec <- c(df$Ad_DTL[1], df$Ad_CC[1], df$Deuce_DTL[1], df$Deuce_CC[1])
    max_winPercent <- max(winPercentVec)
    min_winPercent <- min(winPercentVec)
    countVec <- sort(c(df$Ad_DTL[2], df$Ad_CC[2], df$Deuce_DTL[2], df$Deuce_CC[2]))
    
    g <- rasterGrob(grid2, width=unit(1,"npc"), height=unit(1,"npc"), interpolate = FALSE)
  
    ggplot() +
      labs(title = paste("Volley Distribution -", player), x = "", y = "") +
      xlim(0, 10) +
      ylim(0, 10) +
      annotation_custom(g, xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf) +
      theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),
            axis.text.y = element_blank(), axis.ticks.y = element_blank(),
            axis.title.x = element_blank(), axis.title.y = element_blank(),
            plot.title = element_text(hjust = 0.5, face = "bold")) +
        
      # Labels
      annotate("text", x=3.2, y=0.25, label= paste0("Ad"), cex = 4.5, fontface = 2, col = 'white', family = "Tahoma") +
      annotate("text", x=6.8, y=0.25, label= paste0("Deuce"), cex = 4.5, fontface = 2, col = 'white', family = "Tahoma") +
      annotate("text", x=0.9, y=4.95, label= paste0("Net"), cex = 4.5, fontface = 2, col = 'white', family = "Tahoma") +
      # Ad Down the Line
      annotate("text", x=2.5, y=7.9, label= paste0(df$Ad_DTL[2], " shots"), cex = 5.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
      annotate("text", x=2.5, y=8.35, label= paste0(df$Ad_DTL[1], "% Won"), cex = 4, fontface = 2, 
               col = ifelse(df$Ad_DTL[1] == max_winPercent, 'green', ifelse(df$Ad_DTL[1] == min_winPercent, 'red', 'white')), 
               family = "Tahoma") +
      annotate("text", x=2.5, y=8.75, label= paste0("Down the Line"), cex = 3.5, fontface = 2, col = 'white', family = "Tahoma") +
      # Ad Crosscourt
      annotate("text", x=5.9, y=7.9, label= paste0(df$Ad_CC[2], " shots"), cex = 5.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
      annotate("text", x=5.9, y=8.35, label= paste0(df$Ad_CC[1], "% Won"), cex = 4, fontface = 2, 
               col = ifelse(df$Ad_CC[1] == max_winPercent, 'green', ifelse(df$Ad_CC[1] == min_winPercent, 'red', 'white')), 
               family = "Tahoma") +
      annotate("text", x=5.9, y=8.75, label= paste0("Crosscourt"), cex = 3.5, fontface = 2, col = 'white', family = "Tahoma") +
      # Deuce Crosscourt
      annotate("text", x=4.1, y=7.9, label= paste0(df$Deuce_CC[2], " shots"), cex = 5.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
      annotate("text", x=4.1, y=8.35, label= paste0(df$Deuce_CC[1], "% Won"), cex = 4, fontface = 2, 
               col = ifelse(df$Deuce_CC[1] == max_winPercent, 'green', ifelse(df$Deuce_CC[1] == min_winPercent, 'red', 'white')), 
               family = "Tahoma") +
      annotate("text", x=4.1, y=8.75, label= paste0("Crosscourt"), cex = 3.5, fontface = 2, col = 'white', family = "Tahoma") +
      # Deuce Down the Line
      annotate("text", x=7.5, y=7.9, label= paste0(df$Deuce_DTL[2], " shots"), cex = 5.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
      annotate("text", x=7.5, y=8.35, label= paste0(df$Deuce_DTL[1], "% Won"), cex = 4, fontface = 2, 
               col = ifelse(df$Deuce_DTL[1] == max_winPercent, 'green', ifelse(df$Deuce_DTL[1] == min_winPercent, 'red', 'white')), 
               family = "Tahoma") +
      annotate("text", x=7.5, y=8.75, label= paste0("Down the Line"), cex = 3.5, fontface = 2, col = 'white', family = "Tahoma") +
      # Arrows
      annotate("segment", x = 2.5, y = 0.6, xend = 2.5, yend = 7.5, cex = 1.5, color = 'white', 
               arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
      annotate("segment", x = 2.5, y = 0.6, xend = 5.9, yend = 7.5, cex = 1.5, color = 'white', 
               arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
      annotate("segment", x = 7.5, y = 0.6, xend = 4.1, yend = 7.5, cex = 1.5, color = 'white', 
               arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
      annotate("segment", x = 7.5, y = 0.6, xend = 7.5, yend = 7.5, cex = 1.5, color = 'white', 
               arrow = arrow(length = unit(0.175, "inches"), ends = "last"))
}

volley_distribution(shotdata, player1)
```

# Forehand/Backhand Shot Type
```{r}
shot_type <- function(shotdata, player) {
  
    ad_backhand_perc <- shotdata %>% 
                     filter(shotFhBh == "Backhand" & shotHitBy == player & side == "Ad") %>% 
                     summarise("Type" = "Backhand_perc_ad",
                               "Ad_DTL" = round(((length(which((shotDirection == "Down the Line")))) /
                                 (length(shotDirection)))*100),
                               "Ad_CC" = round(((length(which((shotDirection == "Crosscourt")))) /
                                 (length(shotDirection)))*100))
    
    deuce_backhand_perc <- shotdata %>% 
                        filter(shotFhBh == "Backhand" & shotHitBy == player & side == "Deuce") %>% 
                        summarise("Type" = "Backhand_perc_deuce",
                               "Deuce_DTL" = round(((length(which((shotDirection == "Down the Line")))) /
                                 (length(shotDirection)))*100),
                               "Deuce_CC" = round(((length(which((shotDirection == "Crosscourt")))) /
                                 (length(shotDirection)))*100))
    
    ad_forehand_perc <- shotdata %>% 
                       filter(shotFhBh == "Forehand" & shotHitBy == player & side == "Ad") %>% 
                        summarise("Type" = "forehand_perc_ad",
                               "Ad_DTL" = round(((length(which((shotDirection == "Down the Line")))) /
                                 (length(shotDirection)))*100),
                               "Ad_CC" = round(((length(which((shotDirection == "Crosscourt")))) /
                                 (length(shotDirection)))*100))

    deuce_forehand_perc <- shotdata %>% 
                          filter(shotFhBh == "Forehand" & shotHitBy == player & side == "Deuce") %>% 
                        summarise("Type" = "forehand_perc_deuce",
                               "Deuce_DTL" = round(((length(which((shotDirection == "Down the Line")))) /
                                 (length(shotDirection)))*100),
                               "Deuce_CC" = round(((length(which((shotDirection == "Crosscourt")))) /
                                 (length(shotDirection)))*100))
    
    df <- rbind(cbind(ad_backhand_perc, deuce_backhand_perc), cbind(ad_forehand_perc , deuce_forehand_perc))
    
    g <- rasterGrob(grid3, width=unit(1,"npc"), height=unit(1,"npc"), interpolate = FALSE)
  
    
    # Backhand plot
    backhand_plot <- ggplot() +
    labs(title = paste("Backhand Shot %", player), x = "", y = "") +
    xlim(0, 10) +
    ylim(0, 10) +
    annotation_custom(g, xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf) +
    theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),
          axis.text.y = element_blank(), axis.ticks.y = element_blank(),
          axis.title.x = element_blank(), axis.title.y = element_blank(),
          plot.title = element_text(hjust = 0.5, face = "bold")) + coord_fixed() +
      
    # Labels
    annotate("text", x=3.2, y=-0, label= paste0("Ad"), cex = 4, fontface = 2, col = 'white', family = "Tahoma") +
    annotate("text", x=6.8, y=-0, label= paste0("Deuce"), cex = 4, fontface = 2, col = 'white', family = "Tahoma") +
    annotate("text", x=0.7, y=5.35, label= paste0("Net"), cex = 4, fontface = 2, col = 'white', family = "Tahoma") +
    
    # Ad Down the Line
    annotate("text", x=3, y=7.9, label= paste0(df$Ad_DTL[1], "%"), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=3, y=8.25, label= paste0("Line"), cex = 2.5, fontface = 2, col = 'white', family = "Tahoma") +
    
    # Ad Crosscourt
    annotate("text", x=5.9, y=7.9, label= paste0(df$Ad_CC[1], "%"), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=5.9, y=8.25, label= paste0("Cross"), cex = 2.5, fontface = 2, col = 'white', family = "Tahoma") +

    # Deuce Crosscourt
    annotate("text", x=4.1, y=7.9, label= paste0(df$Deuce_CC[1], "%"), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=4.1, y=8.25, label= paste0("Cross"), cex = 2.5, fontface = 2, col = 'white', family = "Tahoma") +

    # Deuce Down the Line
    annotate("text", x=7, y=7.9, label= paste0(df$Deuce_DTL[1], "%"), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=7, y=8.25, label= paste0("Line"), cex = 2.5, fontface = 2, col = 'white', family = "Tahoma") +
    # Arrows
    annotate("segment", x = 3, y = 0.6, xend = 3, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
    annotate("segment", x = 3, y = 0.6, xend = 5.9, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
    annotate("segment", x = 7, y = 0.6, xend = 4.1, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
    annotate("segment", x = 7, y = 0.6, xend = 7, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last"))
    
    # Forehand plot
    forehand_plot  <- ggplot() +
    labs(title = paste("Forehand Shot %", player), x = "", y = "") +
    xlim(0, 10) +
    ylim(0, 10) +
    annotation_custom(g, xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf) +
    theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),
          axis.text.y = element_blank(), axis.ticks.y = element_blank(),
          axis.title.x = element_blank(), axis.title.y = element_blank(),
          plot.title = element_text(hjust = 0.5, face = "bold")) + coord_fixed() +
      
    # Labels
    annotate("text", x=3.2, y=0, label= paste0("Ad"), cex = 4, fontface = 2, col = 'white', family = "Tahoma") +
    annotate("text", x=6.8, y=0, label= paste0("Deuce"), cex = 4, fontface = 2, col = 'white', family = "Tahoma") +
    annotate("text", x=0.7, y=5.35, label= paste0("Net"), cex = 4, fontface = 2, col = 'white', family = "Tahoma") +
    
    # Ad Down the Line
    annotate("text", x=3, y=7.9, label= paste0(df$Ad_DTL[2], "%"), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=3, y=8.25, label= paste0("Line"), cex = 2.5, fontface = 2, col = 'white', family = "Tahoma") +
    
    # Ad Crosscourt
    annotate("text", x=5.9, y=7.9, label= paste0(df$Ad_CC[2], "%"), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=5.9, y=8.25, label= paste0("Cross"), cex = 2.5, fontface = 2, col = 'white', family = "Tahoma") +

    # Deuce Crosscourt
    annotate("text", x=4.1, y=7.9, label= paste0(df$Deuce_CC[2], "%"), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=4.1, y=8.25, label= paste0("Cross"), cex = 2.5, fontface = 2, col = 'white', family = "Tahoma") +

    # Deuce Down the Line
    annotate("text", x=7, y=7.9, label= paste0(df$Deuce_DTL[2], "%"), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=7, y=8.25, label= paste0("Line"), cex = 2.5, fontface = 2, col = 'white', family = "Tahoma") +
    # Arrows
    annotate("segment", x = 3, y = 0.6, xend = 3, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
    annotate("segment", x = 3, y = 0.6, xend = 5.9, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
    annotate("segment", x = 7, y = 0.6, xend = 4.1, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
    annotate("segment", x = 7, y = 0.6, xend = 7, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last"))
  
  grid.arrange(forehand_plot,backhand_plot ,nrow=1)
}

shot_type(shotdata, player1)
```

```{r}
library(knitr)
library(png)
library(dplyr)
library(grid)
library(ggplot2)
library(gridExtra)
library(tidyr)
shotdata <- read.csv("Shot_Visuals_SpencerJohnson_SamirBanerjee.csv")
player <- "Spencer Johnson"
grid <- readPNG("Full_Court.png")
```

# Plotting Volleys Serve+1
```{r}
# Volley Distribution Function
volley_distribution <- function(shotdata, player) {

    ad_backhand_perc <- shotdata %>% 
  filter(shotFhBh == "Backhand" & shotHitBy == player & side == "Ad" & isVolley == 1 & shotInRally == 3) %>% 
  summarise(
    "Type" = "Backhand_perc_ad",
    "Ad_DTL" = round(((length(which((shotDirection == "Down the Line")))))),
    "Ad_CC" = round(((length(which((shotDirection == "Crosscourt"))))))
  ) %>%
  replace_na(list(
    "Ad_DTL" = 0,
    "Ad_CC" = 0
  ))

# Deuce Backhand Percentage
deuce_backhand_perc <- shotdata %>% 
  filter(shotFhBh == "Backhand" & shotHitBy == player & side == "Deuce" & isVolley == 1 & shotInRally == 3) %>% 
  summarise(
    "Type" = "Backhand_perc_deuce",
    "Deuce_DTL" = round(((length(which((shotDirection == "Down the Line")))))),
    "Deuce_CC" = round(((length(which((shotDirection == "Crosscourt"))))))
  ) %>%
  replace_na(list(
    "Deuce_DTL" = 0,
    "Deuce_CC" = 0
  ))

# Ad Forehand Percentage
ad_forehand_perc <- shotdata %>% 
  filter(shotFhBh == "Forehand" & shotHitBy == player & side == "Ad" & isVolley == 1 & shotInRally == 3) %>% 
  summarise(
    "Type" = "Forehand_perc_ad",
    "Ad_DTL" = round(((length(which((shotDirection == "Down the Line")))))),
    "Ad_CC" = round(((length(which((shotDirection == "Crosscourt"))))))
  ) %>%
  replace_na(list(
    "Ad_DTL" = 0,
    "Ad_CC" = 0
  ))

# Deuce Forehand Percentage
deuce_forehand_perc <- shotdata %>% 
  filter(shotFhBh == "Forehand" & shotHitBy == player & side == "Deuce" & isVolley == 1 & shotInRally == 3) %>% 
  summarise(
    "Type" = "Forehand_perc_deuce",
    "Deuce_DTL" = round(((length(which((shotDirection == "Down the Line")))))),
    "Deuce_CC" = round(((length(which((shotDirection == "Crosscourt"))))))
  ) %>%
  replace_na(list(
    "Deuce_DTL" = 0,
    "Deuce_CC" = 0
  ))

    
    df <- rbind(cbind(ad_backhand_perc, deuce_backhand_perc), cbind(ad_forehand_perc , deuce_forehand_perc))
    
    g <- rasterGrob(grid3, width=unit(1,"npc"), height=unit(1,"npc"), interpolate = FALSE)
  
    # Keeping only first name for format purposes
    player <- strsplit(player, " ")[[1]][1]
# Backhand plot
    backhand_plot <- ggplot() +
    labs(title = paste("Bh Volley Serve+1", player), x = "", y = "") +
    xlim(0, 10) +
    ylim(0, 10) +
    annotation_custom(g, xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf) +
    theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),
          axis.text.y = element_blank(), axis.ticks.y = element_blank(),
          axis.title.x = element_blank(), axis.title.y = element_blank(),
          plot.title = element_text(hjust = 0.5, face = "bold")) + coord_fixed() +
      
    # Labels
    annotate("text", x=1.85, y=7.9, label= paste0("Shots"), cex = 2.1, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=3.2, y=-0, label= paste0("Ad"), cex = 4, fontface = 2, col = 'white', family = "Tahoma") +
    annotate("text", x=6.8, y=-0, label= paste0("Deuce"), cex = 4, fontface = 2, col = 'white', family = "Tahoma") +
    annotate("text", x=0.7, y=5.35, label= paste0("Net"), cex = 4, fontface = 2, col = 'white', family = "Tahoma") +
    
    # Ad Down the Line
    annotate("text", x=3, y=7.9, label= paste0(df$Ad_DTL[1]), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=3, y=8.25, label= paste0("Line"), cex = 2.5, fontface = 2, col = 'white', family = "Tahoma") +
    
    # Ad Crosscourt
    annotate("text", x=5.9, y=7.9, label= paste0(df$Ad_CC[1]), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=5.9, y=8.25, label= paste0("Cross"), cex = 2.5, fontface = 2, col = 'white', family = "Tahoma") +

    # Deuce Crosscourt
    annotate("text", x=4.1, y=7.9, label= paste0(df$Deuce_CC[1]), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=4.1, y=8.25, label= paste0("Cross"), cex = 2.5, fontface = 2, col = 'white', family = "Tahoma") +

    # Deuce Down the Line
    annotate("text", x=7, y=7.9, label= paste0(df$Deuce_DTL[1]), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=7, y=8.25, label= paste0("Line"), cex = 2.5, fontface = 2, col = 'white', family = "Tahoma") +
    # Arrows
    annotate("segment", x = 3, y = 0.6, xend = 3, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
    annotate("segment", x = 3, y = 0.6, xend = 5.9, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
    annotate("segment", x = 7, y = 0.6, xend = 4.1, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
    annotate("segment", x = 7, y = 0.6, xend = 7, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last"))
    
    # Forehand plot
    forehand_plot  <- ggplot() +
    labs(title = paste("Fh Volley Serve+1", player), x = "", y = "") +
    xlim(0, 10) +
    ylim(0, 10) +
    annotation_custom(g, xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf) +
    theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),
          axis.text.y = element_blank(), axis.ticks.y = element_blank(),
          axis.title.x = element_blank(), axis.title.y = element_blank(),
          plot.title = element_text(hjust = 0.5, face = "bold")) + coord_fixed() +
      
    # Labels
    annotate("text", x=1.85, y=7.9, label= paste0("Shots"), cex = 2.1, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=3.2, y=0, label= paste0("Ad"), cex = 4, fontface = 2, col = 'white', family = "Tahoma") +
    annotate("text", x=6.8, y=0, label= paste0("Deuce"), cex = 4, fontface = 2, col = 'white', family = "Tahoma") +
    annotate("text", x=0.7, y=5.35, label= paste0("Net"), cex = 4, fontface = 2, col = 'white', family = "Tahoma") +
    
    # Ad Down the Line
    annotate("text", x=3, y=7.9, label= paste0(df$Ad_DTL[2]), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=3, y=8.25, label= paste0("Line"), cex = 2.5, fontface = 2, col = 'white', family = "Tahoma") +
    
    # Ad Crosscourt
    annotate("text", x=5.9, y=7.9, label= paste0(df$Ad_CC[2]), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=5.9, y=8.25, label= paste0("Cross"), cex = 2.5, fontface = 2, col = 'white', family = "Tahoma") +

    # Deuce Crosscourt
    annotate("text", x=4.1, y=7.9, label= paste0(df$Deuce_CC[2]), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=4.1, y=8.25, label= paste0("Cross"), cex = 2.5, fontface = 2, col = 'white', family = "Tahoma") +

    # Deuce Down the Line
    annotate("text", x=7, y=7.9, label= paste0(df$Deuce_DTL[2]), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=7, y=8.25, label= paste0("Line"), cex = 2.5, fontface = 2, col = 'white', family = "Tahoma") +
    # Arrows
    annotate("segment", x = 3, y = 0.6, xend = 3, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
    annotate("segment", x = 3, y = 0.6, xend = 5.9, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
    annotate("segment", x = 7, y = 0.6, xend = 4.1, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
    annotate("segment", x = 7, y = 0.6, xend = 7, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last"))
  
  grid.arrange(forehand_plot,backhand_plot ,nrow=1)
}

volley_distribution(shotdata, player1)
```

# Plotting Groundstroke Serve+1
```{r}
# Volley Distribution Function
volley_distribution <- function(shotdata, player) {
  # Replace all NaN in isVolley with 0
  shotdata <- shotdata %>%
  mutate(isVolley = replace_na(isVolley, 0))

  
    ad_backhand_perc <- shotdata %>% 
  filter(shotFhBh == "Backhand" & shotHitBy == player & side == "Ad" & isVolley == 0 & shotInRally == 3) %>% 
  summarise(
    "Type" = "Backhand_perc_ad",
    "Ad_DTL" = round(((length(which((shotDirection == "Down the Line")))) / (length(shotDirection)))*100),
    "Ad_CC" = round(((length(which((shotDirection == "Crosscourt")))) / (length(shotDirection)))*100)
  )

# Deuce Backhand Percentage
deuce_backhand_perc <- shotdata %>% 
  filter(shotFhBh == "Backhand" & shotHitBy == player & side == "Deuce" & isVolley == 0 & shotInRally == 3) %>% 
  summarise(
    "Type" = "Backhand_perc_deuce",
    "Deuce_DTL" = round(((length(which((shotDirection == "Down the Line")))) / (length(shotDirection)))*100),
    "Deuce_CC" = round(((length(which((shotDirection == "Crosscourt")))) / (length(shotDirection)))*100)
  )

# Ad Forehand Percentage
ad_forehand_perc <- shotdata %>% 
  filter(shotFhBh == "Forehand" & shotHitBy == player & side == "Ad" & isVolley == 0 & shotInRally == 3) %>% 
  summarise(
    "Type" = "Forehand_perc_ad",
    "Ad_DTL" = round(((length(which((shotDirection == "Down the Line")))) / (length(shotDirection)))*100),
    "Ad_CC" = round(((length(which((shotDirection == "Crosscourt")))) / (length(shotDirection)))*100)
  )

# Deuce Forehand Percentage
deuce_forehand_perc <- shotdata %>% 
  filter(shotFhBh == "Forehand" & shotHitBy == player & side == "Deuce" & isVolley == 0 & shotInRally == 3) %>% 
  summarise(
    "Type" = "Forehand_perc_deuce",
    "Deuce_DTL" = round(((length(which((shotDirection == "Down the Line")))) / (length(shotDirection)))*100),
    "Deuce_CC" = round(((length(which((shotDirection == "Crosscourt")))) / (length(shotDirection)))*100)
  )

    
    df <- rbind(cbind(ad_backhand_perc, deuce_backhand_perc), cbind(ad_forehand_perc , deuce_forehand_perc))
    
    g <- rasterGrob(grid3, width=unit(1,"npc"), height=unit(1,"npc"), interpolate = FALSE)
  
    # Keeping only first name for format purposes
    player <- strsplit(player, " ")[[1]][1]
# Backhand plot
    backhand_plot <- ggplot() +
    labs(title = paste("Bh Groundstroke Serve+1", player), x = "", y = "") +
    xlim(0, 10) +
    ylim(0, 10) +
    annotation_custom(g, xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf) +
    theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),
          axis.text.y = element_blank(), axis.ticks.y = element_blank(),
          axis.title.x = element_blank(), axis.title.y = element_blank(),
          plot.title = element_text(hjust = 0.5, face = "bold")) + coord_fixed() +
      
    # Labels
      annotate("text", x=1.85, y=7.9, label= paste0("Shots"), cex = 2.1, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=3.2, y=-0, label= paste0("Ad"), cex = 4, fontface = 2, col = 'white', family = "Tahoma") +
    annotate("text", x=6.8, y=-0, label= paste0("Deuce"), cex = 4, fontface = 2, col = 'white', family = "Tahoma") +
    annotate("text", x=0.7, y=5.35, label= paste0("Net"), cex = 4, fontface = 2, col = 'white', family = "Tahoma") +
    
    # Ad Down the Line
    annotate("text", x=3, y=7.9, label= paste0(df$Ad_DTL[1], "%"), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=3, y=8.25, label= paste0("Line"), cex = 2.5, fontface = 2, col = 'white', family = "Tahoma") +
    
    # Ad Crosscourt
    annotate("text", x=5.9, y=7.9, label= paste0(df$Ad_CC[1], "%"), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=5.9, y=8.25, label= paste0("Cross"), cex = 2.5, fontface = 2, col = 'white', family = "Tahoma") +

    # Deuce Crosscourt
    annotate("text", x=4.1, y=7.9, label= paste0(df$Deuce_CC[1], "%"), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=4.1, y=8.25, label= paste0("Cross"), cex = 2.5, fontface = 2, col = 'white', family = "Tahoma") +

    # Deuce Down the Line
    annotate("text", x=7, y=7.9, label= paste0(df$Deuce_DTL[1], "%"), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=7, y=8.25, label= paste0("Line"), cex = 2.5, fontface = 2, col = 'white', family = "Tahoma") +
    # Arrows
    annotate("segment", x = 3, y = 0.6, xend = 3, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
    annotate("segment", x = 3, y = 0.6, xend = 5.9, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
    annotate("segment", x = 7, y = 0.6, xend = 4.1, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
    annotate("segment", x = 7, y = 0.6, xend = 7, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last"))
    
    # Forehand plot
    forehand_plot  <- ggplot() +
    labs(title = paste("Fh Groundstroke Serve+1", player), x = "", y = "") +
    xlim(0, 10) +
    ylim(0, 10) +
    annotation_custom(g, xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf) +
    theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),
          axis.text.y = element_blank(), axis.ticks.y = element_blank(),
          axis.title.x = element_blank(), axis.title.y = element_blank(),
          plot.title = element_text(hjust = 0.5, face = "bold")) + coord_fixed() +
      
    # Labels
    annotate("text", x=1.85, y=7.9, label= paste0("Shots"), cex = 2.1, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=3.2, y=0, label= paste0("Ad"), cex = 4, fontface = 2, col = 'white', family = "Tahoma") +
    annotate("text", x=6.8, y=0, label= paste0("Deuce"), cex = 4, fontface = 2, col = 'white', family = "Tahoma") +
    annotate("text", x=0.7, y=5.35, label= paste0("Net"), cex = 4, fontface = 2, col = 'white', family = "Tahoma") +
    
    # Ad Down the Line
    annotate("text", x=3, y=7.9, label= paste0(df$Ad_DTL[2], "%"), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=3, y=8.25, label= paste0("Line"), cex = 2.5, fontface = 2, col = 'white', family = "Tahoma") +
    
    # Ad Crosscourt
    annotate("text", x=5.9, y=7.9, label= paste0(df$Ad_CC[2], "%"), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=5.9, y=8.25, label= paste0("Cross"), cex = 2.5, fontface = 2, col = 'white', family = "Tahoma") +

    # Deuce Crosscourt
    annotate("text", x=4.1, y=7.9, label= paste0(df$Deuce_CC[2], "%"), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=4.1, y=8.25, label= paste0("Cross"), cex = 2.5, fontface = 2, col = 'white', family = "Tahoma") +

    # Deuce Down the Line
    annotate("text", x=7, y=7.9, label= paste0(df$Deuce_DTL[2], "%"), cex = 2.5, fontface = 2, col = '#E6D412', family = "Tahoma") +
    annotate("text", x=7, y=8.25, label= paste0("Line"), cex = 2.5, fontface = 2, col = 'white', family = "Tahoma") +
    # Arrows
    annotate("segment", x = 3, y = 0.6, xend = 3, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
    annotate("segment", x = 3, y = 0.6, xend = 5.9, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
    annotate("segment", x = 7, y = 0.6, xend = 4.1, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last")) +
    annotate("segment", x = 7, y = 0.6, xend = 7, yend = 7.5, cex = 1, color = 'white', 
             arrow = arrow(length = unit(0.175, "inches"), ends = "last"))
  
  grid.arrange(forehand_plot,backhand_plot ,nrow=1)
}

volley_distribution(shotdata, player1)
```

# Net Density Plot
```{r}
pointdata$atNetPlayer1[is.na(pointdata$atNetPlayer1) == TRUE] <- 0
pointdata$atNetPlayer1[pointdata$atNetPlayer1 == player1] <- 1
data_set1 <- pointdata %>%
  select(setNum, gameScore, atNetPlayer1) %>%
  summarise(counts = toString(atNetPlayer1), .by = c(setNum, gameScore))

for (i in 1:nrow(data_set1)){
  data_set1$counts[i] <- sum(!is.na(as.numeric(strsplit(data_set1$counts, ",")[[i]])))
}

data_set1$setNum[data_set1$setNum == 1] <- "Set 1"
data_set1$setNum[data_set1$setNum == 2] <- "Set 2"
data_set1$counts <- as.numeric(data_set1$counts)
data_set1$colour <- ifelse(data_set1$counts == max(data_set1$counts),"red","steelblue")

ggplot(data_set1, aes(x = gameScore, y = counts)) + 
  geom_bar(stat = "identity",
           fill = data_set1$colour,
           position = position_dodge2(padding = 0.05),
           width = 0.4) +
  geom_text(aes(label = ifelse(counts == 3, 3, "")), vjust = -1) + 
  scale_y_continuous(limits = c(0, 3.5)) +
  facet_grid(~ setNum, scales = "free") +
  ggtitle(paste(player1, "At Net Count")) + 
  geom_smooth(aes(group = setNum),stat = "identity", bw = 1000, color = "black") + 
  theme(axis.title.y = element_text(size = 12),
        axis.title.x = element_blank(), 
        panel.background =element_blank(), 
        axis.text = element_text(size = 8), 
        legend.position = "none") + 
  geom_smooth(aes(group = setNum), stat = "identity", bw = 1000, color = "black")
```


