---
title: "Tennis Tables"
author: "Shiyu Murashima"
date: "`r Sys.Date()`"
output: html_document
---

# Libraries
```{r}
library(dplyr)
library(ggplot2)
library(gt)
library(scales)
library(tidyr)
```

# Loading in Data
```{r}
shotdata <- read.csv("SpencerJohnson_AlessioBasile_Shot.csv")
pointdata <- read.csv("SpencerJohnson_AlessioBasile_Point_ForVisuals.csv")
player1 <- "Spencer Johnson"
player2 <- "Alessio Basile"

player_first <- "Spencer"
player_last <- "Johnson"
```

# Quick Statistics Table
```{r}
# quick_percentages <- function(data, player){
#   data$courtSide <- ifelse(data$pointScore %in% c("15-0", "15-30", "30-40", "40-0", "40-40 (Ad)",
#                                             "0-15", "30-15", "40-30", "0-40"),
#                        "Ad", 
#                        ifelse(data$pointScore %in% c("15-40", "30-0", "30-30", "15-15", "40-40 (Deuce)",
#                                                    "40-15", "0-30", "0-0"),
#                               "Deuce",
#                               NA))
#   
#   ad_serve <- data %>% 
#   filter(serverName == player & courtSide == "Ad") %>% 
#   summarise("Server Name" = player,
#             "Ad Serve Wide %" = round(((length(which(firstServeZone == "Wide")) + length(which(secondServeZone == "Wide"))) /
#               (length(which(firstServeZone != "")) + length(which(secondServeZone != ""))))*100),
#             "Ad Serve Body %" = round(((length(which(firstServeZone == "Body")) + length(which(secondServeZone == "Body"))) /
#               (length(which(firstServeZone != "")) + length(which(secondServeZone != ""))))*100),
#             "Ad Serve T %" = round(((length(which(firstServeZone == "T")) + length(which(secondServeZone == "T"))) /
#               (length(which(firstServeZone != "")) + length(which(secondServeZone != ""))))*100))
#   
#   deuce_serve <- data %>% 
#   filter(serverName == player & courtSide == "Deuce") %>% 
#   summarise("Deuce Serve Wide %" = round(((length(which(firstServeZone == "Wide")) + length(which(secondServeZone == "Wide"))) /
#               (length(which(firstServeZone != "")) + length(which(secondServeZone != ""))))*100),
#             "Deuce Serve Body %" = round(((length(which(firstServeZone == "Body")) + length(which(secondServeZone == "Body"))) /
#               (length(which(firstServeZone != "")) + length(which(secondServeZone != ""))))*100),
#             "Deuce Serve T %" = round(((length(which(firstServeZone == "T")) + length(which(secondServeZone == "T"))) /
#               (length(which(firstServeZone != "")) + length(which(secondServeZone != ""))))*100))
#   
#   cbind(ad_serve, deuce_serve)
# }

# quick_counts <- function(data, player){
#   error_table <- data %>% 
#     filter(shotHitBy == player & is.na(isWinner)) %>% 
#     summarise("Server Name" = player,
#               "FH Error Net Count" = length(which(shotFhBh == "Forehand" & isErrorNet == 1)),
#               "FH Error Wide Count" = length(which((shotFhBh == "Forehand" & (isErrorWideL == 1 | isErrorWideR == 1)))),
#               "FH Error Long Count" = length(which(shotFhBh == "Forehand" & isErrorLong == 1)),
#               "BH Error Net Count" = length(which(shotFhBh == "Backhand" & isErrorNet == 1)),
#               "BH Error Wide Count"= length(which((shotFhBh == "Backhand" & (isErrorWideL == 1 | isErrorWideR == 1)))),
#               "BH Error Long Count" = length(which(shotFhBh == "Backhand" & isErrorLong == 1)))
#   
#   net_table <- data %>% 
#     filter(shotHitBy == player) %>% 
#     summarise("Net Count" = length(which(isVolley == 1)))
#   
#   cbind(error_table, net_table)
# }

# rbind(quick_percentages(shotdata, player1), quick_percentages(shotdata, player2))
# rbind(quick_counts(shotdata, player1), quick_counts(shotdata, player2))
```

# Ace/Double Fault Count Table 
```{r}
# Supplement to Summary Stats Visualization
count_table <- function(data){
  data %>% 
    group_by(serverName) %>% 
    filter(isPointStart == 1 & isPointEnd == 1) %>% 
    summarise("Ace Count" = sum(firstServeIn == 1 | secondServeIn == 1),
              "Double Fault Count" = sum(firstServeIn != 1 & secondServeIn != 1))
}

count_table(shotdata)
```

# Approach Shot Table + Visualization
```{r}
# Approach Shot Table Function
approach_table <- function(data, player){
  df1 <- data %>% 
    reframe("approachPercent" = (length(which(isApproach == 1 & shotHitBy == player & is.na(isWinner))) /
                                   length(isApproach))*100,
            "approachWin" = (length(which(isApproach == 1 & shotHitBy == player & is.na(isWinner) & isPointEnd == 1)) /
                               length(isApproach))*100,
            "approachVolleyWin" = (length(which(isApproach == 1 & shotHitBy == player & is.na(isWinner) & 
                                                  isPointEnd == 1 & isVolley == 1)) /
                                     length(isApproach))*100,
            "approachVolleyLose" = (length(which(isApproach == 1 & shotHitBy == player & is.na(isWinner) & 
                                                   isPointEnd != 1 & isVolley == 1)) /
                                      length(isApproach))*100)
  
  df2 <- data %>% 
    filter(isApproach == 1) %>% 
    summarise("approachFH" = (length(which((shotHitBy == player & shotFhBh == "Forehand")))) /
                (length(which(shotHitBy == player & (shotFhBh == "Forehand" | shotFhBh == "Backhand"))))*100,
              "approachBH" = (length(which((shotHitBy == player & shotFhBh == "Backhand")))) /
                (length(which(shotHitBy == player & (shotFhBh == "Forehand" | shotFhBh == "Backhand"))))*100,
              "approachFHWin" = (length(which((shotHitBy == player & shotFhBh == "Forehand" & isPointEnd == 1)))) /
                (length(which(shotHitBy == player & (shotFhBh == "Forehand" | shotFhBh == "Backhand"))))*100,
              "approachBHWin" = (length(which((shotHitBy == player & shotFhBh == "Backhand" & isPointEnd == 1)))) /
                (length(which(shotHitBy == player & (shotFhBh == "Forehand" | shotFhBh == "Backhand"))))*100)
  
  df3 <- data %>% 
    filter(isApproach == 1) %>% 
    summarise("forehandCross" = ((length(which(shotHitBy == player & shotFhBh == "Forehand" & shotDirection == "Crosscourt"))) /
                                   (length(which(shotHitBy == player & shotFhBh == "Forehand" & shotDirection == "Crosscourt")) +
                                   (length(which(shotHitBy == player & shotFhBh == "Forehand" & shotDirection == "Down the Line")))))*100,
              "forehandDL" = ((length(which(shotHitBy == player & shotFhBh == "Forehand" & shotDirection == "Down the Line"))) /
                                   (length(which(shotHitBy == player & shotFhBh == "Forehand" & shotDirection == "Crosscourt")) +
                                   (length(which(shotHitBy == player & shotFhBh == "Forehand" & shotDirection == "Down the Line")))))*100,
              "backhandCross" = ((length(which(shotHitBy == player & shotFhBh == "Backhand" & shotDirection == "Crosscourt"))) /
                                   (length(which(shotHitBy == player & shotFhBh == "Backhand" & shotDirection == "Crosscourt")) +
                                   (length(which(shotHitBy == player & shotFhBh == "Backhand" & shotDirection == "Down the Line")))))*100,
              "backhandDL" = ((length(which(shotHitBy == player & shotFhBh == "Backhand" & shotDirection == "Down the Line"))) /
                                   (length(which(shotHitBy == player & shotFhBh == "Backhand" & shotDirection == "Crosscourt")) +
                                   (length(which(shotHitBy == player & shotFhBh == "Backhand" & shotDirection == "Down the Line")))))*100)
  
  
  df <- data.frame(df1, df2, df3)
  data.frame("Stat" = colnames(df),
             "Percent" = round(as.numeric(unlist(df[1,])), digits = 1))
}

# Approach Shot Count Function
approach_count <- function(data, player){
  data %>% 
    filter(shotHitBy == player) %>% 
    reframe("approachShotCount" = length(which(isApproach == 1)),
            "approachVolleyCount" = length(which(isApproach == 1 & isVolley == 1)))
}

# Approach Shot Plot Function
approach_plot <- function(data){
  data$Stat <- factor(c("Approach %", "Approach Win %", "Volley Win %", "Volley Lose %", 
                        "FH %", "BH %", "FH Win %", "BH Win %", "FH CC %", "FH DTL %", "BH CC %", "BH DTL %"))
  data$Category <- c(rep("Approach Win", 4), rep("Forehand vs Backhand", 4), rep("Forehand", 2), rep("Backhand", 2))
  
  ggplot(data[9:12,], aes(x = Category, y = Percent, fill = Stat)) + 
    geom_bar(position="stack", stat="identity", alpha = 0.7) +
    geom_text(aes(label = Percent), position = position_stack(vjust = 0.5), cex = 6) +
    geom_text(aes(label = Stat), position = position_stack(vjust = 0.5), vjust = 3) +
    scale_fill_manual(values = c("#2D68C4", "#F2A900", "#2D68C4", "#F2A900")) +
    theme(legend.position = "none", 
          plot.title = element_text(hjust = 0.5),
          axis.title.y = element_blank(),
          panel.background = element_rect(fill = "white"),
          panel.grid.major.x = element_line(color = "gray95"),
          panel.grid.minor.x = element_blank(),
          panel.grid.major.y = element_blank(),
          panel.grid.minor.y = element_blank()) +
    labs(title = "Approach FH vs BH, CC vs DTL") +
    coord_flip()
}

temp <- approach_table(shotdata, player1)
temp
approach_count(shotdata, player1)
approach_plot(temp)
```

# Break Point Won Proportion
```{r}
breakPoint <- function(match, playerName) {
  # Clean data for all break points for UCLA player
  bpData <- match[((match$returnerName == playerName) & (match$isBreakPoint == "True")), ]
  isSet1 <- bpData$setNum == 1
  isSet2 <- bpData$setNum == 2
  isSet3 <- bpData$setNum == 3
  bpData$breakPointWon <- bpData$pointWonBy == playerName
  
  
  # Set 1
  set1Data <- bpData[isSet1, ]
  set1_DF <- data.frame(sum(set1Data$breakPointWon), paste0(as.character(round(sum(set1Data$breakPointWon) / nrow(set1Data) * 100, 2)), "%"))
  colnames(set1_DF) <- c("Break Points Won", "Break Point Win Percentage")
  
  # Set 2
  set2Data <- bpData[isSet2, ]
  set2_DF <- data.frame(sum(set2Data$breakPointWon), paste0(as.character(round(sum(set2Data$breakPointWon) / nrow(set2Data) * 100, 2)), "%"))
  colnames(set2_DF) <- c("Break Points Won", "Break Point Win Percentage")
  bpDF <- rbind(set1_DF, set2_DF)
  rownames(bpDF) <- c("Set 1", "Set 2")
  
  # Set 3 
  if (any(isSet3)) {
    set3Data <- bpData[isSet3, ]
    set3_DF <- data.frame(sum(set3Data$breakPointWon), paste0(as.character(round(sum(set3Data$breakPointWon) / nrow(set3Data) * 100, 2)), "%"))
    colnames(set3_DF) <- c("Break Points Won", "Break Point Win Percentage")
    rownames(set3_DF) <- "Set 3"
    bpDF <- rbind(bpDF, set3_DF)
  }
  
  # Full Match
  total_DF <- data.frame(sum(bpData$breakPointWon), paste0(as.character(round(sum(bpData$breakPointWon) / nrow(bpData) * 100, 2)), "%"))
  colnames(total_DF) <- c("Break Points Won", "Break Point Win Percentage")
  rownames(total_DF) <- "Full Match"
  bpDF <- rbind(bpDF, total_DF)
  bpDF
}

breakPoint(pointdata, "Spencer Johnson")
```

# Proportion of Errors for Forehand/Backhand
```{r}
errorPropTable <- function(match, playerName) {
  # Forehand
  fore <- match[((match$pointWonBy != playerName) & (match$errorType != "") & (match$player1LastShotFhBh == "Forehand")), ]
  isWide <- fore$errorType == "Wide Right" | fore$errorType == "Wide Left" 
  isLong <- fore$errorType == "Long" 
  isNet <- fore$errorType == "Net" 
  fore$errorType[isNet] <- "Net"
  fore$errorType[isLong] <- "Long"
  fore$errorType[isWide] <- "Wide"
  errorTypeNames <- c("Net", "Wide", "Long")
  fore$errorType <- factor(fore$errorType, levels = errorTypeNames)
  
  # Backhand
  back <- match[((match$pointWonBy!= playerName) & (match$errorType != "") & (match$player1LastShotFhBh == "Backhand")), ]
  isWide <- back$errorType == "Wide Right" | back$errorType == "Wide Left" 
  isLong <- back$errorType == "Long" 
  isNet <- back$errorType == "Net" 
  back$errorType[isNet] <- "Net"
  back$errorType[isLong] <- "Long"
  back$errorType[isWide] <- "Wide"
  back$errorType <- factor(back$errorType, levels = errorTypeNames)
  
  # Creating Tables
  foreCountTable <- round(table(fore$errorType), 0)
  forePropTable <- paste0(as.character(round(table(fore$errorType) / nrow(fore) * 100, 2)), "%")
  backCountTable <- round(table(back$errorType), 0)
  backPropTable <- paste0(as.character(round(table(back$errorType) / nrow(back) * 100, 2)), "%")
  table <- rbind(foreCountTable, backCountTable, forePropTable, backPropTable)
  rownames(table)
  rownames(table) <- c("Forehand: Error Count", "Backhand: Error Count", "Forehand: Error Percentage", "Backhand: Error Percentage")
  table
}

errorPropTable(pointdata, "Spencer Johnson")
```

# Returns on Serves Table
```{r}
#Create new Data Frame for Sorted Data
df_CLEANED = data.frame()

#Delete all the rows where UCLA is Serving
for (i in 1:nrow(shotdata)){
  row <- shotdata[i,]
  if (row["serverName"] == "Tyler Zink") #replace 'Tyler Zink' with the opponent of the UCLA Player. Make sure it matches name in CSV file.
  {
    df_CLEANED <- rbind(df_CLEANED, row)
  }
}

#Create new Data Frame with one column for number of attempted returns second for number of successful returns
column_headers <- c("tServesAd","tServesDeuce", "bodyServesAd", "bodyServesDeuce", "wideServesAd", "wideServesDeuce", "totals")
row_names <- c("pointWon","returnRate","successfulReturns", "attemptedReturns")

df_SERVES <- data.frame(matrix(0, nrow = 4, ncol = length(column_headers)))
colnames(df_SERVES) <- column_headers
row.names(df_SERVES) <- row_names

new_row <- c(0,0,0,0,0,0,0)
df_SERVES <- rbind(df_SERVES, new_row)

#function to check point Won #check logic
pointWon <- function(row_index, dataFrame){
  
  while(TRUE)
  {
    row <- dataFrame[row_index,]
    if( !is.na(row["isPointEnd"]) )
    {
      break;
    }
    row_index = row_index + 1
  }
  
  row <- dataFrame[row_index,]
  if (row["shotInRally"] %% 2 == 1)
  {
    if (is.na(row["isWinner"]))
    {
      return(1)
    }
    
    else
    {
      return(0)
    }
  }
  
  else if (row["shotInRally"] %% 2 == 0)
  {
    if (!is.na(row["isWinner"]))
    {
      return(1)
    }
    
    else
    {
      return(0)
    }
  }
}


#Get the Attempted Returns & Successful Returns on First Serve
for (i in 1:nrow(df_CLEANED)){
  
  row <- df_CLEANED[i,] #this row gets data for opponents serve type
  next_row = df_CLEANED[i+1,] #this row gets data for UCLA player's return
  
  if (!is.na(row["isPointStart"]) && is.na(row["isPointEnd"])){
    
    serveZone <- df_CLEANED[i,"firstServeZone"]
    side <- df_CLEANED[i, "side"]
    
    #classify the zones:
    if(serveZone == "T"){
      serveZone <- "tServes"
    }
    else if(serveZone == "Body"){
      serveZone <- "bodyServes"
    }
    else if(serveZone == "Wide"){
      serveZone <- "wideServes"
    }
    else{
      #skip data collection if faulty data
      next
    }
    
    category = paste(serveZone, side, sep = "")
    
    if(is.na(next_row["isErrorNet"]) && is.na(next_row["isErrorLong"]) && is.na(next_row["isErrorLong"]) && 
       is.na(next_row["isErrorWideR"]) && is.na(next_row["isErrorWideL"]))
    {
      df_SERVES["successfulReturns",category] <- df_SERVES["successfulReturns",category] + 1
      df_SERVES["pointWon",category] <- df_SERVES["pointWon",category] + pointWon(i,df_CLEANED)
      
    }
    
    df_SERVES["attemptedReturns",category] <- df_SERVES["attemptedReturns",category] + 1
  }
}

#Get the Sums and Set to Total
successful_sum <- rowSums(df_SERVES["successfulReturns",])
attempt_sum <- rowSums(df_SERVES["attemptedReturns",])
point_sums <- rowSums(df_SERVES["pointWon",])
df_SERVES["successfulReturns","totals"] <- successful_sum
df_SERVES["attemptedReturns","totals"] <- attempt_sum
df_SERVES["pointWon","totals"] <- point_sums

#set the values in Return Rate Row
for (i in 1:ncol(df_SERVES))
{
  val1 = df_SERVES["successfulReturns",i]
  val2 = df_SERVES["attemptedReturns",i]
  val3 = df_SERVES["pointWon",i]
  return_percent = (val1/val2)
  point_percent = (val3/val1)
  df_SERVES["returnRate",i] = sprintf("%.1f%%", return_percent * 100)
  df_SERVES["pointWon",i] = sprintf("%.1f%%", point_percent * 100)
}

#Delete last three rows
df_SERVES <- head(df_SERVES,-3)

#Change row names
rownames(df_SERVES) <- c("Point Won Rate", "Serve Return Rate")

#Create a Table for the Results
gt_tbl <- gt(df_SERVES, rownames_to_stub = TRUE)
gt_tbl <- tab_header(gt_tbl, title=md("**Returns on Serves**"), subtitle = NULL, preheader = NULL)
gt_tbl <- tab_source_note(gt_tbl, source_note="*Point Won Rate calculated as number of points won divided by number of succesful returns") #change caption depending on match
gt_tbl <- cols_label(gt_tbl, tServesAd = 'Ad', tServesDeuce = 'Deuce', bodyServesAd = 'Ad', bodyServesDeuce = 'Deuce', wideServesAd = 'Ad', wideServesDeuce = 'Deuce', totals = 'Totals')
gt_tbl <- tab_options(gt_tbl, data_row.padding = px(15), column_labels.padding = px(7), column_labels.padding.horizontal = px(15), container.padding.y = px(15), heading.padding = px(7))
gt_tbl <- cols_align(gt_tbl,align=c("center"),columns = everything())

#Create Spanners
gt_tbl <- tab_spanner(gt_tbl,label = md('**T-Serves**'),columns = 2:3)
gt_tbl <- tab_spanner(gt_tbl,label = md('**Body Serves**'),columns = 4:5)
gt_tbl <- tab_spanner(gt_tbl,label = md('**Wide Serves**'),columns = 6:7)

# Show the gt Table
gt_tbl
```

# Return Error Table
```{r}
shotdata$returnData <- rep(NA, nrow(shotdata))

# Fill NA values in 'side' column
for(i in 1:(dim(shotdata)[1] - 1)) {
  if(shotdata$side[i] == 'Deuce' && shotdata$side[i + 1] == '') {
    shotdata$side[i + 1] = 'Deuce'
  } else if(shotdata$side[i] == 'Ad' && shotdata$side[i + 1] == '') {
    shotdata$side[i + 1] = 'Ad'
  }
}

# For the 'firstServeIn' and 'secondServeIn' columns, you may want to use mutate combined with ifelse
shotdata <- shotdata %>%
  mutate(secondServeIn = if_else(firstServeIn == 1, 0, secondServeIn))

# Fill NA values for 'firstServeIn' and 'secondServeIn' columns
shotdata <- tidyr::fill(shotdata, firstServeIn, .direction = "down")
shotdata <- tidyr::fill(shotdata, secondServeIn, .direction = "down")

# Initialize the 'winner' column with NA values
shotdata$winner <- rep(NA, nrow(shotdata))

# Extract player names (assuming these are constants for the dataset)
player_1 <- shotdata$player1Name[1]
player_2 <- shotdata$player2Name[1]

# Iterate through the rows to determine the winner of each point
for(i in 1:nrow(shotdata)) {
  if(shotdata$isPointEnd[i] == 1 && !is.na(shotdata$isPointEnd[i])) {
    if(shotdata$shotHitBy[i] == player_1) {
      if(shotdata$isWinner[i] == 1 && !is.na(shotdata$winner[i])) {
        shotdata$winner[i] <- player_1
      } else {
        shotdata$winner[i] <- player_2
      }
    } else {
      if(shotdata$isWinner[i] == 1 && !is.na(shotdata$winner[i])) {
        shotdata$winner[i] <- player_2
      } else {
        shotdata$winner[i] <- player_1
      }
    }
  }
}

shotType <- NA

# Iterate over the rows of the data frame
for (i in 1:nrow(shotdata)) {
  # Check if the rally shot is the second shot and set the shot type
  if (shotdata$shotInRally[i] == 2) {
    if (shotdata$shotFhBh[i] == 'Forehand') {
      shotType <- 'Forehand'
    } else {
      shotType <- 'Backhand'
    }
  }
  
  # If the point has ended, assign the shot type to the 'returnData' column and reset shotType
  if (shotdata$isPointEnd[i] == 1 && !is.na(shotdata$isPointEnd[i])) {
    shotdata$returnData[i] <- shotType
    shotType <- NA
  }
}


isError <- rep(NA, nrow(shotdata))

# Loop through the dataframe
for (i in 1:nrow(shotdata)) {
  if (shotdata$shotInRally[i] == 2) {
    if (!is.na(shotdata$isErrorWideR[i]) && shotdata$isErrorWideR[i] == 1) {
      isError[i] <- 'Wide R'
    }
    if (!is.na(shotdata$isErrorWideL[i]) && shotdata$isErrorWideL[i] == 1) {
      isError[i] <- 'Wide L'
    }
    if (!is.na(shotdata$isErrorNet[i]) && shotdata$isErrorNet[i] == 1) {
      isError[i] <- "Net"
    }
    if (!is.na(shotdata$isErrorLong[i]) && shotdata$isErrorLong[i] == 1) {
      isError[i] <- "Long"
    }
  }
}

# Add the isError vector as a new column to the dataframe
shotdata$isError <- isError

data_filtered <- shotdata[, c('pointScore', 'isPointEnd', 'shotInRally', 'side', 'serverName', 'firstServeIn', 
                          'secondServeIn', 'returnData', 'returnerName', 'winner', 'isError')]

# Filter rows where 'isPointEnd' is 1 and 'returnData' is either 'Forehand' or 'Backhand'
data_filtered <- subset(data_filtered, isPointEnd == 1 & returnData %in% c('Forehand', 'Backhand') & shotInRally == 2)

player_1_data = data_filtered[data_filtered['returnerName'] == player_1, ]
player_2_data = data_filtered[data_filtered['returnerName'] == player_2, ]

player_1_first_errors <- player_1_data[player_1_data['firstServeIn'] == 1, ]
player_1_second_errors <- player_1_data[player_1_data['firstServeIn'] == 0, ]
player_2_first_errors <- player_2_data[player_2_data['firstServeIn'] == 1, ]
player_2_second_errors <- player_2_data[player_2_data['firstServeIn'] == 0, ]

player_1_total_serve_returns_first <- shotdata[(shotdata['returnerName'] == player_1) & 
                                             (shotdata['firstServeIn'] == 1) & 
                                             (!is.na(shotdata['isPointStart']) & shotdata['isPointStart'] == 1), ]
player_1_total_serve_returns_second <- shotdata[(shotdata['returnerName'] == player_1) & 
                                              (shotdata['secondServeIn'] == 1) & 
                                              (!is.na(shotdata['isPointStart']) & shotdata['isPointStart'] == 1), ]
player_2_total_serve_returns_first <- shotdata[(shotdata['returnerName'] == player_2) & 
                                             (shotdata['firstServeIn'] == 1) & 
                                             (!is.na(shotdata['isPointStart']) & shotdata['isPointStart'] == 1), ]
player_2_total_serve_returns_second <- shotdata[(shotdata['returnerName'] == player_2) & 
                                              (shotdata['secondServeIn'] == 1) & 
                                              (!is.na(shotdata['isPointStart']) & shotdata['isPointStart'] == 1), ]

string_11 <- paste(nrow(player_1_first_errors), '/', nrow(player_1_total_serve_returns_first), sep="")
string_12 <- paste(nrow(player_1_second_errors), '/', nrow(player_1_total_serve_returns_second), sep="")
string_21 <- paste(nrow(player_2_first_errors), '/', nrow(player_2_total_serve_returns_first), sep="")
string_22 <- paste(nrow(player_2_second_errors), '/', nrow(player_2_total_serve_returns_second), sep="")

prop_stats <- function(x, y) {
  if(y == 0 || x == 0){
    return(0)
  } else {
    return(round(x / y * 100, 2))
  }
}

prop_11 <- prop_stats(nrow(player_1_first_errors), nrow(player_1_total_serve_returns_first))
prop_12 <- prop_stats(nrow(player_1_second_errors), nrow(player_1_total_serve_returns_second))
prop_21 <- prop_stats(nrow(player_2_first_errors), nrow(player_2_total_serve_returns_first))
prop_22 <- prop_stats(nrow(player_2_second_errors), nrow(player_2_total_serve_returns_second))

plot_data <- data.frame(player = c(player_1, player_2),
                        'First Return Error Percent' = c(prop_11, prop_21),
                        'Second Return Error Percent' = c(prop_12, prop_22),
                        error_prop_first = c(paste0(prop_11, '% ', '(', string_11, ')'), paste0(prop_21, '% ', '(', string_21, ')')),
                        error_prop_second = c(paste0(prop_12, '% ', '(', string_12, ')'), paste0(prop_22, '% ', '(', string_22, ')')))

# Reshape data to long format
df_long <- plot_data %>% 
  pivot_longer(cols = c("First.Return.Error.Percent", "Second.Return.Error.Percent"),
               names_to = "serve", 
               values_to = "errorPercent") %>%
  mutate(label = if_else(grepl("First", serve), error_prop_first, error_prop_second))

df_long$serve <- factor(df_long$serve, labels = c("First Return Error Percent", "Second Return Error Percent"))

# Plot
ggplot(df_long, aes(x = player, y = errorPercent, fill = serve)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9), alpha = 0.7) +
  geom_text(aes(label = label),
            position = position_dodge(width = 0.9), vjust = -0.25,
            size = 3.3) +
  scale_fill_manual(
    values = c("First Return Error Percent" = "#2D68C4", "Second Return Error Percent" = "#F2A900"),
    labels = c("First Return Error", "Second Return Error") # Update labels if needed
  ) +
  theme_minimal() +
  labs(title = "Error Percent by Serve Type",
       x = "Player",
       y = "Error Percent (%)",
       fill = "Serve Type") +
  theme(legend.title = element_blank())

player_1_errors <- player_1_data[player_1_data$firstServeIn == 1 || player_1_data$secondServeIn,]
player_2_errors <- player_2_data[player_2_data$firstServeIn == 1 || player_2_data$secondServeIn,]

player_1_errors_ad <- player_1_errors[player_1_errors['side'] == 'Ad', ]
player_1_errors_deuce <- player_1_errors[player_1_errors['side'] == 'Deuce', ]
player_2_errors_ad <- player_2_errors[player_2_errors['side'] == 'Ad', ]
player_2_errors_deuce <- player_2_errors[player_2_errors['side'] == 'Deuce', ]

player_1_total_serve_returns_ad <- shotdata[(shotdata['side'] == 'Ad') &
                                                   (shotdata['returnerName'] == player_1) &
                                          (shotdata['shotInRally'] == 2), ]
player_1_total_serve_returns_deuce <- shotdata[shotdata['side'] == 'Deuce' &
                                                   (shotdata['returnerName'] == player_1) &
                                          (shotdata['shotInRally'] == 2), ]
player_2_total_serve_returns_ad <- shotdata[shotdata['side'] == 'Ad' &
                                                   (shotdata['returnerName'] == player_2) &
                                          (shotdata['shotInRally'] == 2), ]
player_2_total_serve_returns_deuce <- shotdata[shotdata['side'] == 'Deuce' &
                                                   (shotdata['returnerName'] == player_2) &
                                          (shotdata['shotInRally'] == 2), ]

prop_1_ad <- prop_stats(nrow(player_1_errors_ad), nrow(player_1_total_serve_returns_ad))
prop_1_deuce <- prop_stats(nrow(player_1_errors_deuce), nrow(player_1_total_serve_returns_deuce))
prop_2_ad <- prop_stats(nrow(player_2_errors_ad), nrow(player_2_total_serve_returns_ad))
prop_2_deuce <- prop_stats(nrow(player_2_errors_deuce), nrow(player_2_total_serve_returns_deuce))

string_1_ad <- paste(nrow(player_1_errors_ad), '/', nrow(player_1_total_serve_returns_ad), sep="")
string_1_deuce <- paste(nrow(player_1_errors_deuce), '/', nrow(player_1_total_serve_returns_deuce), sep="")
string_2_ad <- paste(nrow(player_2_errors_ad), '/', nrow(player_2_total_serve_returns_ad), sep="")
string_2_deuce <- paste(nrow(player_2_errors_deuce), '/', nrow(player_2_total_serve_returns_deuce), sep="")

string_prop_1_ad <- paste0(prop_1_ad, '% ', '(', string_1_ad, ')')
string_prop_1_deuce <- paste0(prop_1_deuce, '% ', '(', string_1_deuce, ')')
string_prop_2_ad <- paste0(prop_2_ad, '% ', '(', string_2_ad, ')')
string_prop_2_deuce <- paste0(prop_2_deuce, '% ', '(', string_2_deuce, ')')

plot_data_ad_deuce <- data.frame(
  player = c(player_1, player_2),
  adErrorPercent = c(prop_1_ad, prop_2_ad),
  deuceErrorPercent = c(prop_1_deuce, prop_2_deuce),
  adErrorText = c(string_prop_1_ad, string_prop_2_ad),
  deuceErrorText = c(string_prop_1_deuce, string_prop_2_deuce)
)

# First, select only the percentage columns and the player column
percent_df <- plot_data_ad_deuce %>% select(player, adErrorPercent, deuceErrorPercent)

# Then pivot the percent_df to long format
long_percent_df <- percent_df %>% pivot_longer(cols = -player, names_to = "error_type", values_to = "error_percent")

# Now, create a corresponding dataframe for the text columns
text_df <- plot_data_ad_deuce %>% select(player, adErrorText, deuceErrorText)

# Adjust the column names to match those in long_percent_df
names(text_df)[2:3] <- c("adErrorPercent", "deuceErrorPercent")

# Pivot the text_df to long format
long_text_df <- text_df %>% pivot_longer(cols = -player, names_to = "error_type", values_to = "error_text")

# Combine the percent and text dataframes by inner joining them
combined_df <- inner_join(long_percent_df, long_text_df, by = c("player", "error_type"))

# Now you can plot with ggplot2
ggplot(combined_df, aes(x = player, y = error_percent, fill = error_type)) +
  geom_bar(stat = "identity", position = "dodge", alpha = 0.7) +
  geom_text(
    aes(label = error_text), 
    position = position_dodge(width = 0.9), 
    vjust = -0.25,
    size = 3 # Adjust this value to change text size
  ) +
  labs(
    title = "Error Percent by Side",
    x = "Player", 
    y = "Error Percentage",
    fill = "Error Type"
  ) +
  scale_fill_manual(
    values = c("adErrorPercent" = "#2D68C4", "deuceErrorPercent" = "#F2A900"), # Change colors as needed
    labels = c("Ad Error", "Deuce Error") # Change legend labels as needed
  ) +
  theme_minimal() +
  theme(legend.title = element_text(size = 10)) # Change legend title size if needed
```


