---
title: "tennis visualization"
author: "Nathan Kim"
date: "2024-02-11"
output: pdf_document
---
```{r library downloads}
library(readr)
library(dplyr)
library(ggplot2)
library(reshape2)
library(reshape)
```


```{r}
data<-read_csv("GovindNanda_RaphaelPerot_Point_ForVisuals.csv")

## we want to extract playerNet1 and change NA to 0 and get names as 1

data$atNetPlayer1[is.na(data$atNetPlayer1)==TRUE] <- 0
data$atNetPlayer1[data$atNetPlayer1 == "Govind Nanda"] <-1

sum(is.na(data$lastShotResult))

data_set1<-data%>%select(setNum,atNetPlayer1)%>%mutate(games=1:122)%>%group_by(games)

#Graph by game, split by sets
ggplot(data_set1, aes(x = factor(games), y = factor(atNetPlayer1)))+
  geom_bar(stat = "identity", width = 0.1, fill = "blue")+labs(title = "Bar Plot of Player at Net per Game", x = "Game", y = "At Net (1)")+scale_x_discrete(breaks=c(9,17,18,22,23,44,46,51,55,67,80,81,88,89,92,94,96,102,104))+
  facet_grid(~setNum,scales='free')+theme_minimal()
```



