---
title: "volley_distribution"
author: "Tony Jeon"
date: "2024-02-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(png)
library(ggplot2)
library(ggpubr)
library(dplyr)
library(grid)
library(ggtext)

volley_distribution <- function(shotdata, player) {
  
    ad_volley_win <- shotdata %>% 
                     filter(isVolley == 1 & shotHitBy == player & side == "Ad") %>% 
                     summarise("Type" = "Win Percentage",
                               "Ad_DTL" = round(((length(which((shotDirection == "Down the Line"  & pointWonBy == player)))) /
                                 (length(which(shotDirection == "Down the Line"))))*100),
                               "Ad_CC" = round(((length(which((shotDirection == "Crosscourt"  & pointWonBy == player)))) /
                                 (length(which(shotDirection == "Crosscourt"))))*100))
    
    deuce_volley_win <- shotdata %>% 
                        filter(isVolley == 1 & shotHitBy == player & side == "Deuce") %>% 
                        summarise("Type" = "Win Percent Percentage",
                               "Deuce_DTL" = round(((length(which((shotDirection == "Down the Line" & pointWonBy == player)))) /
                                 (length(which(shotDirection == "Down the Line"))))*100),
                               "Deuce_CC" = round(((length(which((shotDirection == "Crosscourt" & pointWonBy == player)))) /
                                 (length(which(shotDirection == "Crosscourt"))))*100))
    
    ad_volley_count <- shotdata %>% 
                       filter(isVolley == 1 & shotHitBy == player & side == "Ad") %>% 
                       summarise("Type" = "Count",
                                 "Ad_DTL" = round((length(which(shotDirection == "Down the Line")))),
                                 "Ad_CC" = round((length(which(shotDirection == "Crosscourt")))))

    deuce_volley_count <- shotdata %>% 
                          filter(isVolley == 1 & shotHitBy == player & side == "Deuce") %>% 
                       summarise("Type" = "Count",
                                 "Deuce_DTL" = round((length(which(shotDirection == "Down the Line")))),
                                 "Deuce_CC" = round((length(which(shotDirection == "Crosscourt")))))
    
    df <- rbind(cbind(ad_volley_win, deuce_volley_win), cbind(ad_volley_count, deuce_volley_count))
    
    grid <- readPNG("Tennis_Court_Half.png")
    g <- rasterGrob(grid, width=unit(1,"npc"), height=unit(1,"npc"), interpolate = FALSE)
  
    ggplot() +
    labs(title = paste("Volley Distribution -", player), x = "", y = "") +
    xlim(0, 10) +
    ylim(0, 10) +
    annotation_custom(g, xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf) +
    # Labels for Side
    annotate("text", x=3.25, y=5, label= paste0("Ad"), cex = 4.5, fontface = 2, col = 'white') +
    annotate("text", x=6.875, y=5, label= paste0("Deuce"), cex = 4.5, fontface = 2, col = 'white') +
    # Ad Down the Line
    annotate("text", x=2.5, y=8.5, label= paste0(df$Ad_DTL[1], "%"), cex = 4.5, fontface = 2, col = 'white') +
    annotate("text", x=2.5, y=9, label= paste0(df$Ad_DTL[2], " shots"), cex = 4.5, fontface = 2, col = 'white') +
    annotate("text", x=2.5, y=9.5, label= paste0("DTL"), cex = 4.5, fontface = 2, col = 'white') +
    # Ad Crosscourt
    annotate("text", x=4, y=8.5, label= paste0(df$Ad_CC[1], "%"), cex = 4.5, fontface = 2, col = 'white') +
    annotate("text", x=4, y=9, label= paste0(df$Ad_CC[2], " shots"), cex = 4.5, fontface = 2, col = 'white') +
    annotate("text", x=4, y=9.5, label= paste0("CC"), cex = 4.5, fontface = 2, col = 'white') +
    # Deuce Crosscourt
    annotate("text", x=6, y=8.5, label= paste0(df$Deuce_CC[1], "%"), cex = 4.5, fontface = 2, col = 'white') +
    annotate("text", x=6, y=9, label= paste0(df$Deuce_CC[2], " shots"), cex = 4.5, fontface = 2, col = 'white') +
    annotate("text", x=6, y=9.5, label= paste0("CC"), cex = 4.5, fontface = 2, col = 'white') +
    # Deuce Down the Line
    annotate("text", x=7.5, y=8.5, label= paste0(df$Deuce_DTL[1], "%"), cex = 4.5, fontface = 2, col = 'white') +
    annotate("text", x=7.5, y=9, label= paste0(df$Deuce_DTL[2], " shots"), cex = 4.5, fontface = 2, col = 'white') +
    annotate("text", x=7.5, y=9.5, label= paste0("DTL"), cex = 4.5, fontface = 2, col = 'white') +
    # Arrows
    annotate("segment", x = 2.5, y = 0, xend = 2.5, yend = 8, cex = 1.25, color = 'white', arrow = arrow(length = unit(0.15, "inches"), ends = "last")) +
    annotate("segment", x = 2.5, y = 0, xend = 5.875, yend = 8, cex = 1.25, color = 'white', arrow = arrow(length = unit(0.15, "inches"), ends = "last")) +
    annotate("segment", x = 7.5, y = 0, xend = 4.125, yend = 8, cex = 1.25, color = 'white', arrow = arrow(length = unit(0.15, "inches"), ends = "last")) +
    annotate("segment", x = 7.5, y = 0, xend = 7.5, yend = 8, cex = 1.25, color = 'white', arrow = arrow(length = unit(0.15, "inches"), ends = "last")) 
}
```

```{r}
shotdata1 <- read.csv("GiacomoShot.csv")
player1 <- "Giacomo Revelli"
volley_distribution(shotdata1, player1)
```


